// Normalized Enterprise Permission Taxonomy (P2)
// Convention: domain.action (Canonical) with full backward-compatibility for legacy action codes

export type PermissionCategory =
  | 'APPLICATIONS'
  | 'UNDERWRITING'
  | 'CREDIT_ASSESSMENT'
  | 'BRANCH_MANAGEMENT'
  | 'DISBURSEMENTS'
  | 'COLLECTIONS'
  | 'CONFIGURATION'
  | 'PRIVACY_AUDIT'
  | 'TENANT_ADMIN'
  | 'RISK_GOVERNANCE'
  | 'FRAUD_OPS'
  | 'PAYMENTS_SETTLEMENTS'
  | 'ACCOUNTING_FINANCE'
  | 'COMMUNICATIONS_SUPPORT'
  | 'ANALYTICS_MIS'
  | 'CORE_LENDING_OPS'
  | 'PARTNER_ECOSYSTEM';

// Canonical domain.action permission keys
export type CanonicalPermissionKey =
  // Customer Domain
  | 'customer.view'
  | 'customer.create'
  | 'customer.edit'
  | 'customer.delete'
  | 'customer.kyc'

  // Application Domain
  | 'application.view'
  | 'application.create'
  | 'application.edit'
  | 'application.submit'
  | 'application.review'
  | 'application.return'
  | 'application.resubmit'
  | 'application.approve'
  | 'application.reject'

  // Credit Assessment Domain
  | 'credit.view'
  | 'credit.assess'
  | 'credit.recommend'
  | 'credit.bank_intelligence'
  | 'credit.fraud_score'

  // Underwriting & Sanction Domain
  | 'underwriting.view'
  | 'underwriting.decide'
  | 'underwriting.condition'
  | 'underwriting.override'
  | 'underwriting.kfs_generate'
  | 'underwriting.bureau_view'
  | 'underwriting.committee_vote'

  // Approval Authority Matrix & Delegations
  | 'approval.view'
  | 'approval.review'
  | 'approval.approve'
  | 'approval.reject'
  | 'approval.send_back'
  | 'approval.escalate'
  | 'approval.delegate'
  | 'approval.queue.view'
  | 'authority.view'
  | 'authority.create'
  | 'authority.edit'
  | 'authority.activate'
  | 'authority.archive'
  | 'delegation.view'
  | 'delegation.create'
  | 'delegation.edit'
  | 'delegation.revoke'

  // Offer Engine & Pricing
  | 'offer.view'
  | 'offer.generate'
  | 'offer.edit'
  | 'offer.regenerate'
  | 'offer.accept'
  | 'offer.decline'
  | 'offer.cancel'
  | 'offer.simulate'
  | 'offer.pricing.view'
  | 'offer.pricing.configure'
  | 'offer.policy.view'
  | 'offer.policy.create'
  | 'offer.policy.edit'
  | 'offer.policy.activate'
  | 'offer.policy.archive'

  // Credit Limit Engine & Revolving Facilities
  | 'credit_limit.view'
  | 'credit_limit.create'
  | 'credit_limit.evaluate'
  | 'credit_limit.approve'
  | 'credit_limit.increase'
  | 'credit_limit.decrease'
  | 'credit_limit.suspend'
  | 'credit_limit.freeze'
  | 'credit_limit.resume'
  | 'credit_limit.close'
  | 'credit_facility.view'
  | 'credit_facility.create'
  | 'credit_facility.edit'
  | 'drawdown.view'
  | 'drawdown.request'
  | 'drawdown.approve'
  | 'drawdown.cancel'
  | 'credit_limit.policy.view'
  | 'credit_limit.policy.create'
  | 'credit_limit.policy.edit'
  | 'credit_limit.policy.activate'
  | 'credit_limit.policy.archive'

  // Disbursement & Payout Domain
  | 'disbursement.view'
  | 'disbursement.verify'
  | 'disbursement.execute'
  | 'disbursement.penny_drop'
  | 'disbursement.reconcile'
  | 'payout.view'
  | 'payout.create'
  | 'payout.initiate'
  | 'payout.approve'
  | 'payout.cancel'
  | 'payout.retry'

  // Loan Servicing Domain
  | 'loan.view'
  | 'loan.manage'
  | 'loan.restructure'
  | 'loan.settle'
  | 'loan.close'
  | 'loan.noc_issue'

  // Payments, Settlements & Disputes Domain
  | 'payment.view'
  | 'payment.create'
  | 'payment.record'
  | 'payment.verify'
  | 'payment.initiate'
  | 'payment.confirm'
  | 'payment.refund'
  | 'payment.reverse'
  | 'settlement.view'
  | 'settlement.confirm'
  | 'settlement.reconcile'
  | 'dispute.view'
  | 'dispute.manage'
  | 'recon.view'
  | 'recon.execute'
  | 'recon.adjust'
  | 'recon.resolve'

  // Collections & Recovery Domain
  | 'collection.view'
  | 'collection.manage'
  | 'collection.assign'
  | 'collection.contact'
  | 'collection.activity'
  | 'collection.ptp'
  | 'collection.create_ptp'
  | 'collection.update_ptp'
  | 'collection.escalate'
  | 'collection.waive_penalty'
  | 'collection.settle'
  | 'collection.settlement.request'
  | 'collection.settlement.approve'
  | 'collection.writeoff'
  | 'collection.writeoff.request'
  | 'collection.writeoff.approve'
  | 'collection.policy.view'
  | 'collection.policy.create'
  | 'collection.policy.edit'
  | 'collection.policy.activate'
  | 'collection.analytics.view'

  // Financial Core, GL & Accounting
  | 'finance.gl.view'
  | 'finance.gl.post'
  | 'finance.trial_balance'
  | 'finance.accrual.run'
  | 'finance.npa.view'
  | 'finance.recon.view'
  | 'finance.recon.execute'
  | 'accounting.view'
  | 'accounting.dashboard.view'
  | 'accounting.coa.view'
  | 'accounting.coa.create'
  | 'accounting.coa.edit'
  | 'accounting.coa.activate'
  | 'accounting.coa.archive'
  | 'accounting.coa.manage'
  | 'accounting.period.view'
  | 'accounting.period.open'
  | 'accounting.period.soft_close'
  | 'accounting.period.close'
  | 'accounting.period.reopen'
  | 'accounting.period.manage'
  | 'accounting.journal.view'
  | 'accounting.journal.create'
  | 'accounting.journal.edit'
  | 'accounting.journal.submit'
  | 'accounting.journal.approve'
  | 'accounting.journal.post'
  | 'accounting.journal.reverse'
  | 'accounting.journal.reject'
  | 'accounting.trial_balance.view'
  | 'accounting.financial_statements.view'
  | 'accounting.cash_flow.view'
  | 'accounting.receivables.view'
  | 'accounting.payables.view'
  | 'accounting.payables.create'
  | 'accounting.payables.approve'
  | 'accounting.payables.pay'
  | 'accounting.payables.manage'
  | 'accounting.accruals.view'
  | 'accounting.accruals.create'
  | 'accounting.accruals.approve'
  | 'accounting.accruals.post'
  | 'accounting.accruals.run'
  | 'accounting.accruals.reverse'
  | 'accounting.tax.view'
  | 'accounting.tax.manage'
  | 'accounting.tax.report'
  | 'accounting.suspense.view'
  | 'accounting.suspense.clear'
  | 'accounting.suspense.manage'
  | 'accounting.controls.view'

  // Business Rules Engine (BRE) & Policy Studio
  | 'bre.view'
  | 'bre.edit'
  | 'bre.simulate'
  | 'decision.view'
  | 'decision.evaluate'
  | 'decision.simulate'
  | 'decision.override'
  | 'decision.policy.view'
  | 'decision.policy.create'
  | 'decision.policy.edit'
  | 'decision.policy.activate'
  | 'decision.policy.archive'
  | 'decision.rules.view'
  | 'decision.rules.create'
  | 'decision.rules.edit'
  | 'decision.rules.activate'
  | 'decision.rules.archive'

  // Risk & Fraud Intelligence Domain
  | 'risk.view'
  | 'risk.view_signals'
  | 'risk.evaluate'
  | 'risk.manage_policies'
  | 'risk.override'
  | 'risk.fraud_intel'
  | 'risk.early_warnings'
  | 'fraud.view_cases'
  | 'fraud.investigate'
  | 'fraud.manage_rules'
  | 'fraud.override'

  // Compliance, Privacy & Audit
  | 'audit.view'
  | 'audit.export'
  | 'audit.verify'
  | 'compliance.view'
  | 'privacy.view'
  | 'privacy.manage'
  | 'privacy.purge'

  // Partner & Ecosystem (P7 Normalized)
  | 'partner.dashboard.view'
  | 'partner.users.view'
  | 'partner.users.manage'
  | 'partner.applications.create'
  | 'partner.applications.view'
  | 'partner.applications.update'
  | 'partner.applications.submit'
  | 'partner.applications.documents.view'
  | 'partner.applications.documents.upload'
  | 'partner.application.status.view'
  | 'partner.offers.view'
  | 'partner.offers.accept'
  | 'partner.customers.view'
  | 'partner.webhooks.view'
  | 'partner.webhooks.replay'
  | 'partner.api_credentials.view'
  | 'partner.api_credentials.create'
  | 'partner.api_credentials.rotate'
  | 'partner.api_credentials.revoke'
  | 'partner.commissions.view'
  | 'partner.settlements.view'
  | 'partner.support.create'
  | 'partner.support.view'
  | 'partner.view'
  | 'partner.manage'
  | 'partner.credentials.manage'
  | 'partner.webhooks.manage'
  | 'partner.reports.view'

  // Communications & Support
  | 'communications.view'
  | 'communications.send'
  | 'communications.template.view'
  | 'communications.template.create'
  | 'communications.template.edit'
  | 'communications.template.activate'
  | 'communications.template.manage'
  | 'communications.templates.view'
  | 'communications.templates.manage'
  | 'communications.policy.view'
  | 'communications.policy.create'
  | 'communications.policy.edit'
  | 'communications.policy.manage'
  | 'communications.policies.view'
  | 'communications.policies.manage'
  | 'communications.delivery.view'
  | 'communications.preference.view'
  | 'communications.preference.manage'
  | 'communications.preferences.view'
  | 'communications.preferences.manage'
  | 'support.view'
  | 'support.ticket.view'
  | 'support.ticket.create'
  | 'support.ticket.assign'
  | 'support.ticket.reply'
  | 'support.ticket.resolve'
  | 'support.ticket.reopen'
  | 'support.ticket.escalate'
  | 'support.tickets.view'
  | 'support.tickets.manage'
  | 'support.tickets.escalate'
  | 'support.complaint.view'
  | 'support.complaint.manage'
  | 'support.complaints.view'
  | 'support.complaints.manage'
  | 'support.reports.view'
  | 'support.sla'

  // Products & Workflows
  | 'product.view'
  | 'product.create'
  | 'product.edit'
  | 'product.activate'
  | 'product.deactivate'
  | 'product.archive'
  | 'product.configure'
  | 'product.simulate'
  | 'workflow.view'
  | 'workflow.create'
  | 'workflow.edit'
  | 'workflow.activate'
  | 'workflow.archive'
  | 'workflow.manage'

  // Platform & Tenant Administration
  | 'tenant.view'
  | 'tenant.create'
  | 'tenant.edit'
  | 'tenant.manage'
  | 'branch.view'
  | 'branch.manage'
  | 'user.view'
  | 'user.create'
  | 'user.edit'
  | 'user.manage'
  | 'role.view'
  | 'role.manage'
  | 'config.view'
  | 'config.manage'
  | 'branding.view'
  | 'branding.manage'
  | 'integration.view'
  | 'integration.manage'
  | 'settings.manage'
  | 'system.observability'

  // Analytics & Command Center
  | 'analytics.view'
  | 'analytics.portfolio'
  | 'analytics.credit'
  | 'analytics.risk'
  | 'analytics.fraud'
  | 'analytics.collections'
  | 'analytics.finance'
  | 'analytics.partners'
  | 'analytics.branches'
  | 'analytics.products'
  | 'analytics.operations'
  | 'analytics.support'
  | 'analytics.command_center'
  | 'reports.view'
  | 'reports.create'
  | 'reports.edit'
  | 'reports.execute'
  | 'reports.export'
  | 'reports.share'
  | 'report.create'
  | 'report.edit'
  | 'report.execute'
  | 'report.export'
  | 'dashboard.view'
  | 'dashboard.configure';

// Legacy UPPERCASE Permission Codes for backward compatibility
export type LegacyPermissionCode =
  | 'APPLICATIONS_CREATE'
  | 'APPLICATIONS_VIEW'
  | 'APPLICATIONS_ASSIGN'
  | 'APPLICATIONS_REVIEW'
  | 'APPLICATIONS_APPROVE'
  | 'APPLICATIONS_REJECT'
  | 'UNDERWRITING_VIEW_BUREAU'
  | 'UNDERWRITING_RUN_AI_ASSIST'
  | 'UNDERWRITING_APPROVE_EXCEPTION'
  | 'UNDERWRITING_COMMITTEE_VOTE'
  | 'CREDIT_ASSESSMENT_VIEW'
  | 'CREDIT_ASSESSMENT_EVALUATE'
  | 'CREDIT_ASSESSMENT_SUBMIT'
  | 'CREDIT_ASSESSMENT_FORWARD'
  | 'VIEW_BRANCH_APPLICATIONS'
  | 'VIEW_CUSTOMER_DETAILS'
  | 'VIEW_DOCUMENTS'
  | 'VIEW_CREDIT_ANALYST_REPORT'
  | 'VIEW_RISK_ASSESSMENT'
  | 'VIEW_REPAYMENT_ASSESSMENT'
  | 'REVIEW_APPLICATION'
  | 'APPROVE_WITHIN_DELEGATED_LIMIT'
  | 'SEND_BACK_FOR_CORRECTION'
  | 'ESCALATE_TO_UNDERWRITER'
  | 'ADD_MANAGER_REMARKS'
  | 'DISBURSEMENTS_INITIATE_PAYOUT'
  | 'DISBURSEMENTS_APPROVE_MAKER_CHECKER'
  | 'DISBURSEMENTS_EXECUTE_TRANSFER'
  | 'DISBURSEMENTS_RECONCILE'
  | 'COLLECTIONS_VIEW_DPD'
  | 'COLLECTIONS_ASSIGN'
  | 'COLLECTIONS_CONTACT'
  | 'COLLECTIONS_RECORD_PTP'
  | 'COLLECTIONS_UPDATE_PTP'
  | 'COLLECTIONS_ESCALATE'
  | 'COLLECTIONS_INITIATE_RECOVERY'
  | 'COLLECTIONS_WAIVE_PENALTY'
  | 'COLLECTIONS_SETTLE_LOAN'
  | 'COLLECTIONS_SETTLEMENT_REQUEST'
  | 'COLLECTIONS_SETTLEMENT_APPROVE'
  | 'COLLECTIONS_WRITEOFF_REQUEST'
  | 'COLLECTIONS_WRITEOFF_APPROVE'
  | 'COLLECTIONS_POLICY_VIEW'
  | 'COLLECTIONS_POLICY_MANAGE'
  | 'COLLECTIONS_ANALYTICS_VIEW'
  | 'CONFIGURATION_VIEW_POLICIES'
  | 'CONFIGURATION_DRAFT_POLICY'
  | 'CONFIGURATION_PUBLISH_POLICY'
  | 'CONFIGURATION_CONFIGURE_INTEGRATIONS'
  | 'PRIVACY_VIEW_CONSENT_REGISTRY'
  | 'AUDIT_EXPORT_EVIDENCE_PACKAGE'
  | 'AUDIT_VERIFY_CHAIN'
  | 'PRIVACY_PURGE_PII'
  | 'TENANT_MANAGE_USERS'
  | 'TENANT_ASSIGN_ROLES'
  | 'TENANT_VIEW_OPERATIONS_CENTER'
  | 'TENANT_CONFIGURE_BRANDING'
  | 'RISK_VIEW_SIGNALS'
  | 'RISK_EVALUATE'
  | 'RISK_MANAGE_POLICIES'
  | 'RISK_OVERRIDE'
  | 'FRAUD_VIEW_CASES'
  | 'FRAUD_INVESTIGATE'
  | 'FRAUD_MANAGE_RULES'
  | 'FRAUD_OVERRIDE'
  | 'PAYMENTS_VIEW'
  | 'PAYMENTS_CREATE'
  | 'PAYMENTS_CONFIRM'
  | 'PAYMENTS_REFUND'
  | 'PAYMENTS_REVERSE'
  | 'SETTLEMENTS_VIEW'
  | 'SETTLEMENTS_RECONCILE'
  | 'PAYOUTS_VIEW'
  | 'PAYOUTS_INITIATE'
  | 'PAYOUTS_APPROVE'
  | 'RECONCILIATION_VIEW'
  | 'RECONCILIATION_EXECUTE'
  | 'RECONCILIATION_ADJUST'
  | 'RECONCILIATION_RESOLVE'
  | 'DISPUTES_VIEW'
  | 'DISPUTES_MANAGE'
  | 'ACCOUNTING_VIEW'
  | 'ACCOUNTING_DASHBOARD_VIEW'
  | 'COA_VIEW'
  | 'COA_CREATE'
  | 'COA_EDIT'
  | 'COA_ACTIVATE'
  | 'COA_ARCHIVE'
  | 'JOURNAL_VIEW'
  | 'JOURNAL_CREATE'
  | 'JOURNAL_EDIT'
  | 'JOURNAL_SUBMIT'
  | 'JOURNAL_APPROVE'
  | 'JOURNAL_POST'
  | 'JOURNAL_REJECT'
  | 'JOURNAL_REVERSE'
  | 'PERIOD_VIEW'
  | 'PERIOD_OPEN'
  | 'PERIOD_SOFT_CLOSE'
  | 'PERIOD_CLOSE'
  | 'PERIOD_REOPEN'
  | 'TRIAL_BALANCE_VIEW'
  | 'FINANCIAL_STATEMENTS_VIEW'
  | 'CASH_FLOW_VIEW'
  | 'RECEIVABLES_VIEW'
  | 'PAYABLES_VIEW'
  | 'PAYABLES_CREATE'
  | 'PAYABLES_APPROVE'
  | 'PAYABLES_PAY'
  | 'ACCRUAL_VIEW'
  | 'ACCRUAL_CREATE'
  | 'ACCRUAL_APPROVE'
  | 'ACCRUAL_POST'
  | 'ACCRUAL_REVERSE'
  | 'TAX_VIEW'
  | 'TAX_MANAGE'
  | 'TAX_REPORT'
  | 'SUSPENSE_MANAGE'
  | 'FINANCE_CONTROLS_VIEW'
  | 'COMMUNICATIONS_VIEW'
  | 'COMMUNICATIONS_SEND'
  | 'COMMUNICATIONS_TEMPLATE_VIEW'
  | 'COMMUNICATIONS_TEMPLATE_CREATE'
  | 'COMMUNICATIONS_TEMPLATE_EDIT'
  | 'COMMUNICATIONS_TEMPLATE_ACTIVATE'
  | 'COMMUNICATIONS_POLICY_VIEW'
  | 'COMMUNICATIONS_POLICY_CREATE'
  | 'COMMUNICATIONS_POLICY_EDIT'
  | 'COMMUNICATIONS_DELIVERY_VIEW'
  | 'COMMUNICATIONS_PREFERENCE_VIEW'
  | 'COMMUNICATIONS_PREFERENCE_MANAGE'
  | 'SUPPORT_VIEW'
  | 'SUPPORT_TICKET_CREATE'
  | 'SUPPORT_TICKET_ASSIGN'
  | 'SUPPORT_TICKET_REPLY'
  | 'SUPPORT_TICKET_RESOLVE'
  | 'SUPPORT_TICKET_REOPEN'
  | 'SUPPORT_TICKET_ESCALATE'
  | 'SUPPORT_COMPLAINT_VIEW'
  | 'SUPPORT_COMPLAINT_MANAGE'
  | 'SUPPORT_REPORTS_VIEW'
  | 'ANALYTICS_VIEW'
  | 'ANALYTICS_PORTFOLIO'
  | 'ANALYTICS_CREDIT'
  | 'ANALYTICS_RISK'
  | 'ANALYTICS_FRAUD'
  | 'ANALYTICS_COLLECTIONS'
  | 'ANALYTICS_FINANCE'
  | 'ANALYTICS_PARTNERS'
  | 'ANALYTICS_BRANCHES'
  | 'ANALYTICS_PRODUCTS'
  | 'ANALYTICS_OPERATIONS'
  | 'ANALYTICS_SUPPORT'
  | 'ANALYTICS_COMMAND_CENTER'
  | 'REPORT_VIEW'
  | 'REPORT_CREATE'
  | 'REPORT_EDIT'
  | 'REPORT_EXECUTE'
  | 'REPORT_EXPORT'
  | 'REPORT_SHARE'
  | 'DASHBOARD_VIEW'
  | 'DASHBOARD_CONFIGURE';

// Unified PermissionCode Union supporting both canonical and legacy notations
export type PermissionCode = CanonicalPermissionKey | LegacyPermissionCode | (string & {});

export type ResourceScope = 'GLOBAL' | 'TENANT' | 'REGION' | 'BRANCH' | 'PARTNER';

export interface PermissionDefinition {
  code: PermissionCode;
  category: PermissionCategory;
  name: string;
  description: string;
  riskLevel: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
}

export interface CustomRole {
  id: string;
  tenantId: string;
  code: string;
  name: string;
  description: string;
  isSystemRole: boolean;
  parentRoleCode?: string;
  permissions: PermissionCode[];
  scope: ResourceScope;
  sanctionLimitAmount?: number;
  payoutLimitAmount?: number;
  createdAt: string;
  updatedAt: string;
}

export interface CreateCustomRoleDto {
  code: string;
  name: string;
  description: string;
  parentRoleCode?: string;
  permissions: PermissionCode[];
  scope?: ResourceScope;
  sanctionLimitAmount?: number;
  payoutLimitAmount?: number;
  allowSodOverride?: boolean;
  overrideJustification?: string;
}

export interface UpdateRoleDto {
  name?: string;
  description?: string;
  permissions?: PermissionCode[];
  scope?: ResourceScope;
  sanctionLimitAmount?: number;
  payoutLimitAmount?: number;
}

export interface SodRule {
  id: string;
  code: string;
  name: string;
  description: string;
  conflictingPermissions: [PermissionCode, PermissionCode];
  severity: 'CRITICAL_BLOCK' | 'WARNING';
}

export interface SodConflictCheckResult {
  hasConflict: boolean;
  hasCriticalBlock: boolean;
  conflicts: Array<{
    ruleCode: string;
    ruleName: string;
    description: string;
    conflictingPair: [PermissionCode, PermissionCode];
    severity: 'CRITICAL_BLOCK' | 'WARNING';
  }>;
}
