/**
 * Phase 16: Frontend Workspaces & Portals Client Config & Fallbacks
 */

import {
  PortalKey,
  WorkspaceKey,
  PortalDefinition,
  WorkspaceDefinition,
  FeatureFlagConfig,
} from './workspace.types';

export const CLIENT_PORTALS: Record<PortalKey, PortalDefinition> = {
  PUBLIC: {
    key: 'PUBLIC',
    name: 'Public Portal',
    description: 'Public lending marketing and authentication portal',
    iconName: 'Globe',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['*'],
    isEnabled: true,
  },
  OPERATIONS: {
    key: 'OPERATIONS',
    name: 'Operations Portal',
    description: 'Loan origination, onboarding, application processing, and branch workflows',
    iconName: 'Activity',
    defaultWorkspace: 'OPERATIONS_LENDING',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'BRANCH_MANAGER', 'OPERATIONS_MANAGER'],
    isEnabled: true,
  },
  CREDIT: {
    key: 'CREDIT',
    name: 'Credit & Underwriting Portal',
    description: 'Credit assessment, risk scoring, underwriting queues, and credit facilities',
    iconName: 'Calculator',
    defaultWorkspace: 'CREDIT_ASSESSMENT',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER', 'RISK_ANALYST', 'RISK_MANAGER'],
    isEnabled: true,
  },
  COLLECTIONS: {
    key: 'COLLECTIONS',
    name: 'Collections & Recovery Portal',
    description: 'Overdue delinquency aging, promise-to-pay tracking, and legal recovery',
    iconName: 'AlertCircle',
    defaultWorkspace: 'COLLECTIONS_DELINQUENCY',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    isEnabled: true,
  },
  FINANCE: {
    key: 'FINANCE',
    name: 'Finance & Accounting Portal',
    description: 'General ledger, payments ledger, bank reconciliation, treasury and payouts',
    iconName: 'Scale',
    defaultWorkspace: 'FINANCE_GL',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER', 'TREASURY_MANAGER'],
    isEnabled: true,
  },
  MANAGEMENT: {
    key: 'MANAGEMENT',
    name: 'Management & Analytics Portal',
    description: 'Executive command center, MIS reporting, portfolio analytics, and SLA telemetry',
    iconName: 'Cpu',
    defaultWorkspace: 'MANAGEMENT_COMMAND_CENTER',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'RISK_MANAGER', 'EXECUTIVE'],
    isEnabled: true,
  },
  ADMIN: {
    key: 'ADMIN',
    name: 'Administration Portal',
    description: 'Institutional settings, user roles, BRE rule studio, workflows, and audit compliance',
    iconName: 'ShieldCheck',
    defaultWorkspace: 'ADMIN_ACCESS_CONTROL',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'AUDITOR'],
    isEnabled: true,
  },
  BORROWER: {
    key: 'BORROWER',
    name: 'Borrower Digital Portal',
    description: 'Direct-to-consumer digital borrowing, KFS acceptance, and loan servicing',
    iconName: 'User',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  PARTNER: {
    key: 'PARTNER',
    name: 'Partner & LSP Portal',
    description: 'Embedded lending gateway, partner applications, webhooks, and credentials',
    iconName: 'Handshake',
    defaultWorkspace: 'PARTNER_EMBEDDED_HUB',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'ADMIN'],
    isEnabled: true,
  },
};

export const CLIENT_WORKSPACES: Record<WorkspaceKey, WorkspaceDefinition> = {
  OPERATIONS_LENDING: {
    key: 'OPERATIONS_LENDING',
    name: 'Lending Operations',
    shortLabel: 'Lending Ops',
    description: 'Loan origination, applicant queue, application tracking, and servicing',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'FileText',
    defaultRoute: '/dashboard',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'OPERATIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  OPERATIONS_BRANCH: {
    key: 'OPERATIONS_BRANCH',
    name: 'Branch Management Desk',
    shortLabel: 'Branch Desk',
    description: 'Branch proposal reviews, staff oversight, and delegated sanction limits',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Building2',
    defaultRoute: '/branch-review',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  OPERATIONS_ONBOARDING: {
    key: 'OPERATIONS_ONBOARDING',
    name: 'Customer Onboarding',
    shortLabel: 'Onboarding',
    description: 'Customer directory, KYC verification desk, and document management',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Users',
    defaultRoute: '/customers',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  CREDIT_ASSESSMENT: {
    key: 'CREDIT_ASSESSMENT',
    name: 'Credit Assessment Desk',
    shortLabel: 'Credit Desk',
    description: 'Financial capacity analysis, FOIR calculation, and credit recommendations',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'Calculator',
    defaultRoute: '/credit-assessment',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  CREDIT_UNDERWRITING: {
    key: 'CREDIT_UNDERWRITING',
    name: 'Underwriting & Sanctions',
    shortLabel: 'Underwriting',
    description: 'Final sanction decisions, policy exception approvals, and authority matrix',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'FileCheck',
    defaultRoute: '/underwriting',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'UNDERWRITER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  CREDIT_RISK_STUDIO: {
    key: 'CREDIT_RISK_STUDIO',
    name: 'Risk & Fraud Intelligence',
    shortLabel: 'Risk Studio',
    description: '6-pillar risk scoring, fraud graph visualization, and credit facility rules',
    portal: 'CREDIT',
    department: 'RISK',
    iconName: 'ShieldAlert',
    defaultRoute: '/risk',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'RISK_ANALYST', 'RISK_MANAGER', 'FRAUD_ANALYST'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  COLLECTIONS_DELINQUENCY: {
    key: 'COLLECTIONS_DELINQUENCY',
    name: 'Delinquency & DPD Aging',
    shortLabel: 'Delinquency',
    description: 'Overdue case queues, collector assignment, and Promise-to-Pay (PTP) logs',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertCircle',
    defaultRoute: '/collections',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  COLLECTIONS_RECOVERY: {
    key: 'COLLECTIONS_RECOVERY',
    name: 'Recovery & NPA Monitoring',
    shortLabel: 'NPA Recovery',
    description: 'NPA asset quality tracking, early warning triggers, and legal notices',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertTriangle',
    defaultRoute: '/npa-monitoring',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  COLLECTIONS_SETTLEMENTS: {
    key: 'COLLECTIONS_SETTLEMENTS',
    name: 'Settlements & Debt Relief',
    shortLabel: 'Settlements',
    description: 'One-Time Settlement (OTS) requests, penalty waivers, and loan restructuring',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'Scale',
    defaultRoute: '/settlements',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  FINANCE_GL: {
    key: 'FINANCE_GL',
    name: 'General Ledger (GL)',
    shortLabel: 'General Ledger',
    description: 'Double-entry trial balance, chart of accounts, and financial MIS statements',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Scale',
    defaultRoute: '/general-ledger',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  FINANCE_TREASURY: {
    key: 'FINANCE_TREASURY',
    name: 'Treasury & Disbursements',
    shortLabel: 'Treasury',
    description: 'Disbursement batch maker-checker, payout execution, and repayment receipts',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Wallet',
    defaultRoute: '/disbursements',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  FINANCE_RECONCILIATION: {
    key: 'FINANCE_RECONCILIATION',
    name: 'Banking & Reconciliation',
    shortLabel: 'Reconciliation',
    description: 'Bank statement 3-way matching, payment gateway settlements, and float audit',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Receipt',
    defaultRoute: '/reconciliation',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  MANAGEMENT_COMMAND_CENTER: {
    key: 'MANAGEMENT_COMMAND_CENTER',
    name: 'Executive Command Center',
    shortLabel: 'Command Center',
    description: 'Centralized executive operational health, AI telemetry, and portfolio KPI radar',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'Cpu',
    defaultRoute: '/command-center',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'EXECUTIVE'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  MANAGEMENT_ANALYTICS: {
    key: 'MANAGEMENT_ANALYTICS',
    name: 'Portfolio Analytics & MIS',
    shortLabel: 'Analytics',
    description: 'Origination funnel, 2D risk-fraud matrices, collector productivity, and custom reports',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'BarChart3',
    defaultRoute: '/analytics',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  MANAGEMENT_EARLY_WARNINGS: {
    key: 'MANAGEMENT_EARLY_WARNINGS',
    name: 'Early Warning Center',
    shortLabel: 'Early Warnings',
    description: 'Pre-delinquency telemetry, bureau degradation alerts, and liquidity forecast',
    portal: 'MANAGEMENT',
    department: 'RISK',
    iconName: 'AlertTriangle',
    defaultRoute: '/early-warnings',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'RISK_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  ADMIN_ACCESS_CONTROL: {
    key: 'ADMIN_ACCESS_CONTROL',
    name: 'Staff & Access Control',
    shortLabel: 'Access Control',
    description: 'User management, RBAC custom roles, permission matrix, and staff directory',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'KeyRound',
    defaultRoute: '/users',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  ADMIN_RULES_STUDIO: {
    key: 'ADMIN_RULES_STUDIO',
    name: 'BRE & Workflow Studio',
    shortLabel: 'Rules Studio',
    description: 'Business Rule Engine visual editor, approval matrix, and state machine workflows',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'Workflow',
    defaultRoute: '/bre-studio',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  ADMIN_CONFIGURATION: {
    key: 'ADMIN_CONFIGURATION',
    name: 'Institutional Config & Branding',
    shortLabel: 'Config & Branding',
    description: 'Multi-tenant lender parameters, loan products, branches, white-label branding, and integrations',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'Sliders',
    defaultRoute: '/configuration',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  ADMIN_AUDIT_COMPLIANCE: {
    key: 'ADMIN_AUDIT_COMPLIANCE',
    name: 'Audit & DPDP Compliance',
    shortLabel: 'Compliance',
    description: 'Immutable SHA-256 evidence packages, DPDP consent registry, and regulatory audits',
    portal: 'ADMIN',
    department: 'COMPLIANCE',
    iconName: 'ShieldCheck',
    defaultRoute: '/compliance',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'AUDITOR'],
    displayOrder: 4,
    status: 'ACTIVE',
  },
  BORROWER_SELF_SERVICE: {
    key: 'BORROWER_SELF_SERVICE',
    name: 'Borrower Self-Service Hub',
    shortLabel: 'My Account',
    description: 'Customer application status, KFS acceptance, repayments, and NOC certificates',
    portal: 'BORROWER',
    department: 'CUSTOMER_SERVICE',
    iconName: 'User',
    defaultRoute: '/borrower',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  PARTNER_EMBEDDED_HUB: {
    key: 'PARTNER_EMBEDDED_HUB',
    name: 'Partner / LSP Embedded Desk',
    shortLabel: 'Partner Hub',
    description: 'Embedded loan origination pipeline, DSA agents, API keys, and webhook logs',
    portal: 'PARTNER',
    department: 'PARTNER_NETWORK',
    iconName: 'Handshake',
    defaultRoute: '/partner',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
};

export const DEFAULT_CLIENT_FEATURE_FLAGS: FeatureFlagConfig = {
  enableBreStudio: true,
  enableAiCommandCenter: true,
  enableDigiLockerKyc: true,
  enableInstantEnach: true,
  enableCollectionsAutomation: true,
  enableAdvancedReporting: true,
  enableWhiteLabelBranding: true,
  enableBorrowerApp: true,
  enablePartnerLspPlatform: true,
};
