import { Router } from 'express';
import authRoutes from '../modules/auth/auth.routes';
import customerRoutes from '../modules/customer/customer.routes';
import documentRoutes from '../modules/documents/document.routes';
import productRoutes from '../modules/product/product.routes';
import applicationRoutes from '../modules/application/application.routes';
import eligibilityRoutes from '../modules/eligibility/eligibility.routes';
import riskRoutes from '../modules/risk/risk.routes';
import underwritingRoutes from '../modules/underwriting/underwriting.routes';
import loanRoutes from '../modules/loans/loan.routes';
import disbursementRoutes from '../modules/disbursements/disbursement.routes';
import paymentRoutes from '../modules/payments/payment.routes';
import collectionRoutes from '../modules/collections/collection.routes';
import restructuringRoutes from '../modules/restructuring/restructuring.routes';
import reportRoutes from '../modules/reports/report.routes';
import branchRoutes from '../modules/branches/branch.routes';
import userRoutes from '../modules/users/user.routes';
import settingRoutes from '../modules/settings/settings.routes';
import notificationRoutes from '../modules/notifications/notification.routes';
import auditRoutes from '../modules/audit/audit.routes';
import financeRoutes from '../modules/finance/finance.routes';
import aiRoutes from '../modules/ai/ai.routes';
import integrationRoutes from '../modules/integrations/integration.routes';
import bankIntelligenceRoutes from '../modules/bank-intelligence/bank-intelligence.routes';
import { decisionIntelligenceRoutes } from '../modules/decision-intelligence/decision-intelligence.routes';
import { earlyWarningRoutes } from '../modules/early-warning/early-warning.routes';
import { decisionSimulatorRoutes } from '../modules/decision-simulator/decision-simulator.routes';
import { reconciliationRoutes } from '../modules/reconciliation/reconciliation.routes';
import { partnerRoutes } from '../modules/partners/partner.routes';
import { communicationRoutes } from '../modules/communication/communication.routes';
import { commandCenterRoutes } from '../modules/command-center/command-center.routes';
import { tenantRoutes } from '../modules/tenants/tenant.routes';
import { configurationRoutes } from '../modules/configuration/configuration.routes';
import { brandingRoutes } from '../modules/branding/branding.routes';
import { securityRoutes } from '../modules/security/security.routes';
import { workerRoutes } from '../modules/jobs/worker.routes';
import { hadrRoutes } from '../modules/hadr/hadr.routes';
import { observabilityRoutes } from '../modules/observability/observability.routes';
import { complianceRoutes } from '../modules/compliance/compliance.routes';
import { privacyRoutes } from '../modules/privacy/consent.routes';
import { roleRoutes } from '../modules/roles/role.routes';
import { workflowRoutes } from '../modules/workflows/workflow.routes';
import { deploymentRoutes } from '../modules/deployment/deployment.routes';
import { clientOnboardingRoutes } from '../modules/onboarding/client-onboarding.routes';
import { slaSupportRoutes } from '../modules/support/sla-support.routes';

const router = Router();

router.use('/auth', authRoutes);
router.use('/customers', customerRoutes);
router.use('/documents', documentRoutes);
router.use('/loan-products', productRoutes);
router.use('/applications', applicationRoutes);
router.use('/eligibility', eligibilityRoutes);
router.use('/risk', riskRoutes);
router.use('/underwriting', underwritingRoutes);
router.use('/loans', loanRoutes);
router.use('/disbursements', disbursementRoutes);
router.use('/payments', paymentRoutes);
router.use('/collections', collectionRoutes);
router.use('/restructuring', restructuringRoutes);
router.use('/reports', reportRoutes);
router.use('/branches', branchRoutes);
router.use('/users', userRoutes);
router.use('/settings', settingRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit', auditRoutes);
router.use('/finance', financeRoutes);
router.use('/ai', aiRoutes);
router.use('/integrations', integrationRoutes);
router.use('/bank-intelligence', bankIntelligenceRoutes);
router.use('/decision-intelligence', decisionIntelligenceRoutes);
router.use('/early-warnings', earlyWarningRoutes);
router.use('/decision-simulator', decisionSimulatorRoutes);
router.use('/reconciliation', reconciliationRoutes);
router.use('/partners', partnerRoutes);
router.use('/communications', communicationRoutes);
router.use('/command-center', commandCenterRoutes);
router.use('/tenants', tenantRoutes);
router.use('/configuration', configurationRoutes);
router.use('/branding', brandingRoutes);
router.use('/security', securityRoutes);
router.use('/jobs', workerRoutes);
router.use('/hadr', hadrRoutes);
router.use('/compliance', complianceRoutes);
router.use('/privacy', privacyRoutes);
router.use('/roles', roleRoutes);
router.use('/workflows', workflowRoutes);
router.use('/deployment', deploymentRoutes);
router.use('/client-onboarding', clientOnboardingRoutes);
router.use('/support', slaSupportRoutes);
router.use(observabilityRoutes);

export default router;
