import { PermissionKey } from '../permissions/permissions.types';
import { WorkspaceId } from './workspaces.types';

export type NavCategoryKey =
  | 'OVERVIEW'
  | 'CUSTOMERS'
  | 'LENDING'
  | 'SERVICING'
  | 'INSIGHTS'
  | 'ADMINISTRATION';

export interface AppNavItem {
  key: string;
  label: string;
  href: string;
  iconName: string;
  workspace: WorkspaceId;
  group: NavCategoryKey;
  requiredPermission?: PermissionKey;
  requiredAnyPermissions?: PermissionKey[];
  description?: string;
}

// Master Centralized Navigation Definition for Adyapan Lending OS
export const CENTRALIZED_NAVIGATION: AppNavItem[] = [
  // 1. OVERVIEW
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    iconName: 'LayoutDashboard',
    workspace: 'OPERATIONS',
    group: 'OVERVIEW',
  },
  {
    key: 'command-center',
    label: 'AI Command Center',
    href: '/command-center',
    iconName: 'Cpu',
    workspace: 'PLATFORM',
    group: 'OVERVIEW',
    requiredPermission: 'analytics.command_center',
  },
  {
    key: 'branch-review',
    label: 'Branch Applications Desk',
    href: '/branch-review',
    iconName: 'FileCheck',
    workspace: 'BRANCH',
    group: 'OVERVIEW',
    requiredPermission: 'approval.view',
  },

  // 2. CUSTOMERS
  {
    key: 'customers',
    label: 'Customers',
    href: '/customers',
    iconName: 'Users',
    workspace: 'OPERATIONS',
    group: 'CUSTOMERS',
    requiredPermission: 'customer.view',
  },

  // 3. LENDING (LOS & ORIGINATION)
  {
    key: 'applications',
    label: 'Loan Applications',
    href: '/applications',
    iconName: 'FileText',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'application.view',
  },
  {
    key: 'returned-applications',
    label: 'Returned Applications',
    href: '/returned-applications',
    iconName: 'RotateCcw',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'application.return',
  },
  {
    key: 'credit-assessment',
    label: 'Credit Assessment',
    href: '/credit-assessment',
    iconName: 'Calculator',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'credit.assess',
  },
  {
    key: 'underwriting',
    label: 'Underwriting Queue',
    href: '/underwriting',
    iconName: 'FileCheck',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'underwriting.view',
  },
  {
    key: 'approval-queue',
    label: 'Approval Authority Queue',
    href: '/approval-queue',
    iconName: 'Inbox',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'approval.queue.view',
  },
  {
    key: 'offers',
    label: 'Loan Offers',
    href: '/offers',
    iconName: 'Sparkles',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'offer.view',
  },
  {
    key: 'credit-facilities',
    label: 'Credit Facilities & Limits',
    href: '/credit-facilities',
    iconName: 'CreditCard',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'credit_facility.view',
    description: 'Revolving credit limits, available balances, and drawdown desk',
  },
  {
    key: 'disbursements',
    label: 'Disbursements',
    href: '/disbursements',
    iconName: 'Wallet',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'disbursement.view',
  },
  {
    key: 'loan-products',
    label: 'Loan Products',
    href: '/loan-products',
    iconName: 'Building2',
    workspace: 'PLATFORM',
    group: 'LENDING',
    requiredPermission: 'product.view',
  },
  {
    key: 'partners',
    label: 'Partners & DSAs',
    href: '/partners',
    iconName: 'Handshake',
    workspace: 'OPERATIONS',
    group: 'LENDING',
    requiredPermission: 'partner.view',
  },

  // 4. SERVICING (LMS, PAYMENTS, GL, COLLECTIONS)
  {
    key: 'loans',
    label: 'Loan Accounts',
    href: '/loans',
    iconName: 'DollarSign',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'loan.view',
  },
  {
    key: 'payments',
    label: 'Payments Ledger',
    href: '/payments',
    iconName: 'Receipt',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'payment.view',
  },
  {
    key: 'general-ledger',
    label: 'General Ledger (GL)',
    href: '/general-ledger',
    iconName: 'Scale',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'finance.gl.view',
  },
  {
    key: 'reconciliation',
    label: 'Accounting & Recon',
    href: '/reconciliation',
    iconName: 'Scale',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'finance.recon.view',
  },
  {
    key: 'collections',
    label: 'Collections & Delinquency',
    href: '/collections',
    iconName: 'AlertCircle',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'collection.view',
  },
  {
    key: 'communications',
    label: 'Omnichannel Hub',
    href: '/communications',
    iconName: 'Mail',
    workspace: 'OPERATIONS',
    group: 'SERVICING',
    requiredPermission: 'communications.view',
  },

  // 5. INSIGHTS & RISK
  {
    key: 'reports',
    label: 'Reports & Analytics',
    href: '/reports',
    iconName: 'BarChart3',
    workspace: 'OPERATIONS',
    group: 'INSIGHTS',
    requiredPermission: 'reports.view',
  },
  {
    key: 'npa-monitoring',
    label: 'NPA & Asset Quality',
    href: '/npa-monitoring',
    iconName: 'AlertTriangle',
    workspace: 'OPERATIONS',
    group: 'INSIGHTS',
    requiredPermission: 'finance.npa.view',
  },
  {
    key: 'fraud-intelligence',
    label: 'Fraud & Anomaly Intelligence',
    href: '/fraud-intelligence',
    iconName: 'ShieldAlert',
    workspace: 'OPERATIONS',
    group: 'INSIGHTS',
    requiredPermission: 'risk.fraud_intel',
  },
  {
    key: 'early-warnings',
    label: 'Early Warning Center',
    href: '/early-warnings',
    iconName: 'AlertTriangle',
    workspace: 'OPERATIONS',
    group: 'INSIGHTS',
    requiredPermission: 'risk.early_warnings',
  },
  {
    key: 'emi-calculator',
    label: 'EMI Calculator',
    href: '/emi-calculator',
    iconName: 'Calculator',
    workspace: 'OPERATIONS',
    group: 'INSIGHTS',
  },
  {
    key: 'compliance',
    label: 'Regulatory & Compliance',
    href: '/compliance',
    iconName: 'ShieldCheck',
    workspace: 'COMPLIANCE',
    group: 'INSIGHTS',
    requiredPermission: 'compliance.view',
  },
  {
    key: 'operations',
    label: 'Operations & Observability',
    href: '/operations',
    iconName: 'Activity',
    workspace: 'PLATFORM',
    group: 'INSIGHTS',
    requiredPermission: 'system.observability',
  },

  // 6. ADMINISTRATION & PLATFORM GOVERNANCE
  {
    key: 'tenants',
    label: 'Multi-Tenant Institutions',
    href: '/tenants',
    iconName: 'Building2',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'tenant.view',
    description: 'Enterprise B2B tenant onboarding, readiness evaluation, and directory',
  },
  {
    key: 'tenant-settings',
    label: 'Tenant Configuration Studio',
    href: '/tenant-settings',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'tenant.view',
    description: 'Unified multi-engine configuration, branches, staff, and branding studio',
  },
  {
    key: 'branches',
    label: 'Branch Directory',
    href: '/branches',
    iconName: 'Building2',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'branch.view',
  },
  {
    key: 'users',
    label: 'Staff Users',
    href: '/users',
    iconName: 'KeyRound',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'user.view',
  },
  {
    key: 'roles',
    label: 'Roles & Permissions',
    href: '/roles',
    iconName: 'KeyRound',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'role.view',
  },
  {
    key: 'workflows',
    label: 'Workflow Studio',
    href: '/workflows',
    iconName: 'Workflow',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'workflow.view',
  },
  {
    key: 'bre-studio',
    label: 'BRE & Policy Studio',
    href: '/bre-studio',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'bre.view',
  },
  {
    key: 'authority-matrix',
    label: 'Approval Authority Matrix',
    href: '/authority-matrix',
    iconName: 'ShieldCheck',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'authority.view',
  },
  {
    key: 'pricing-policies',
    label: 'Pricing & Offer Policies',
    href: '/pricing-policies',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'offer.policy.view',
  },
  {
    key: 'credit-policies',
    label: 'Credit Limit Policies',
    href: '/credit-policies',
    iconName: 'ShieldAlert',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'credit_limit.policy.view',
    description: 'Exposure caps, risk grade limits, and revolving drawdown parameters',
  },
  {
    key: 'configuration',
    label: 'Policy Configuration',
    href: '/configuration',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'config.view',
  },
  {
    key: 'branding',
    label: 'Branding & White-Label',
    href: '/branding',
    iconName: 'Palette',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'branding.manage',
  },
  {
    key: 'integrations',
    label: 'Integration Hub',
    href: '/integrations',
    iconName: 'Cpu',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'integration.view',
  },
  {
    key: 'privacy',
    label: 'Privacy & Consent',
    href: '/privacy',
    iconName: 'ShieldCheck',
    workspace: 'COMPLIANCE',
    group: 'ADMINISTRATION',
    requiredPermission: 'privacy.manage',
  },
  {
    key: 'audit-logs',
    label: 'Audit Logs',
    href: '/audit-logs',
    iconName: 'ScrollText',
    workspace: 'COMPLIANCE',
    group: 'ADMINISTRATION',
    requiredPermission: 'audit.view',
  },
  {
    key: 'settings',
    label: 'System Settings',
    href: '/settings',
    iconName: 'ShieldCheck',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'settings.manage',
  },

  // 7. BORROWER SELF-SERVICE (Phase 7 Digital Lending)
  {
    key: 'borrower-dashboard',
    label: 'My Account & Loans',
    href: '/dashboard',
    iconName: 'LayoutDashboard',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'borrower-apply',
    label: 'Apply for Loan',
    href: '/apply',
    iconName: 'Sparkles',
    workspace: 'BORROWER',
    group: 'LENDING',
  },
  {
    key: 'borrower-credit',
    label: 'Credit Line & Drawdowns',
    href: '/credit',
    iconName: 'Zap',
    workspace: 'BORROWER',
    group: 'LENDING',
  },
  {
    key: 'borrower-documents',
    label: 'Document Vault & KYC',
    href: '/documents',
    iconName: 'FolderArchive',
    workspace: 'BORROWER',
    group: 'CUSTOMERS',
  },

  // 8. PARTNER / LSP EMBEDDED LENDING PORTAL (Phase 8)
  {
    key: 'partners-admin',
    label: 'Partners & LSPs',
    href: '/partners',
    iconName: 'Handshake',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'partner.view',
    description: 'Manage fintech partners, LSPs, embedded integrations, and credentials',
  },
  {
    key: 'partner-hub',
    label: 'Partner Dashboard',
    href: '/partner',
    iconName: 'LayoutDashboard',
    workspace: 'PARTNER',
    group: 'OVERVIEW',
  },
  {
    key: 'partner-applications',
    label: 'Applications Pipeline',
    href: '/partner/applications',
    iconName: 'FileText',
    workspace: 'PARTNER',
    group: 'LENDING',
  },
  {
    key: 'partner-customers',
    label: 'Customers & Consents',
    href: '/partner/customers',
    iconName: 'Users',
    workspace: 'PARTNER',
    group: 'CUSTOMERS',
  },
  {
    key: 'partner-offers',
    label: 'Loan Offers & KFS',
    href: '/partner/offers',
    iconName: 'Tag',
    workspace: 'PARTNER',
    group: 'LENDING',
  },
  {
    key: 'partner-loans',
    label: 'Active Loans',
    href: '/partner/loans',
    iconName: 'CreditCard',
    workspace: 'PARTNER',
    group: 'SERVICING',
  },
  {
    key: 'partner-credit',
    label: 'Credit Facilities',
    href: '/partner/credit',
    iconName: 'Layers',
    workspace: 'PARTNER',
    group: 'LENDING',
  },
  {
    key: 'partner-api-credentials',
    label: 'API Credentials',
    href: '/partner/api-credentials',
    iconName: 'Key',
    workspace: 'PARTNER',
    group: 'ADMINISTRATION',
  },
  {
    key: 'partner-webhooks',
    label: 'Webhooks & Logs',
    href: '/partner/webhooks',
    iconName: 'Webhook',
    workspace: 'PARTNER',
    group: 'ADMINISTRATION',
  },
  {
    key: 'partner-reports',
    label: 'Commissions & Reports',
    href: '/partner/reports',
    iconName: 'DollarSign',
    workspace: 'PARTNER',
    group: 'INSIGHTS',
  },
  {
    key: 'partner-settings',
    label: 'Organization Settings',
    href: '/partner/settings',
    iconName: 'Settings',
    workspace: 'PARTNER',
    group: 'ADMINISTRATION',
  },
];
