import { PermissionKey } from '../permissions/permissions.types';
import { WorkspaceId } from './workspaces.types';

export type NavCategoryKey =
  | 'OVERVIEW'
  | 'ORIGINATION'
  | 'CREDIT_ASSESSMENT'
  | 'RISK_FRAUD'
  | 'FINANCIAL_OPS'
  | 'SERVICING'
  | 'COLLECTIONS'
  | 'PARTNERSHIP'
  | 'SUPPORT'
  | 'GOVERNANCE'
  | 'ADMINISTRATION';

export interface AppNavItem {
  key: string;
  label: string;
  href: string;
  iconName: string;
  workspace: WorkspaceId;
  group: NavCategoryKey;
  requiredPermission?: PermissionKey;
  requiredAnyPermissions?: PermissionKey[];
  description?: string;
  isLocked?: boolean;
  lockReason?: string;
}

// Master Centralized Navigation Definition for Adyapan Lending OS (P3 Consolidated 7 Hubs)
export const CENTRALIZED_NAVIGATION: AppNavItem[] = [
  // ─── HUB 1: ORIGINATION & FRONT-OFFICE ───
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    iconName: 'LayoutDashboard',
    workspace: 'ORIGINATION',
    group: 'OVERVIEW',
  },
  {
    key: 'leads',
    label: 'Leads & Sourcing',
    href: '/leads',
    iconName: 'Megaphone',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'application.view', // Note: Need a specific permission if available, fallback to application.view for now
    description: 'New lead creation, online submissions, and conversion',
  },
  {
    key: 'customers',
    label: 'Customers & KYC',
    href: '/customers',
    iconName: 'Users',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'customer.view',
    description: 'Customer profile, contact information, and KYC initiation',
  },
  {
    key: 'applications',
    label: 'Loan Applications',
    href: '/applications',
    iconName: 'FileText',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'application.view',
    description: 'Application creation, product selection, and borrower details',
  },
  {
    key: 'documents',
    label: 'Document Collection',
    href: '/documents',
    iconName: 'FileCheck',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'customer.kyc',
    description: 'Dynamic document checklists based on applicant profile',
  },
  {
    key: 'review-complete',
    label: 'Review & Complete',
    href: '/review-complete',
    iconName: 'CheckSquare',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'application.view',
    description: 'Final internal preparation checklist before credit submission',
  },
  {
    key: 'submit-to-credit',
    label: 'Submit to Credit',
    href: '/submit-to-credit',
    iconName: 'Send',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'application.view',
    description: 'Validation and final submission to Credit Analyst queue',
  },
  {
    key: 'returned-applications',
    label: 'Returned Applications',
    href: '/returned-applications',
    iconName: 'RotateCcw',
    workspace: 'ORIGINATION',
    group: 'ORIGINATION',
    requiredPermission: 'application.return',
    description: 'Corrections and resubmission desk for underwriter-returned proposals',
  },

  // ─── HUB 2: CREDIT & ASSESSMENT (EXACT 6 AUTHORITATIVE ITEMS) ───
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/dashboard',
    iconName: 'LayoutDashboard',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
  },
  {
    key: 'customers',
    label: 'Customers',
    href: '/customers',
    iconName: 'Users',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'customer.view',
    description: 'Borrower proposals forwarded by Loan Officers for credit assessment',
  },
  {
    key: 'documents',
    label: 'Documents',
    href: '/documents',
    iconName: 'FileCheck',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'application.view',
    description: 'Borrower case dossiers, verification checklist, and document inspection',
  },
  {
    key: 'credit-assessment',
    label: 'Credit Assessment',
    href: '/credit-assessment',
    iconName: 'Calculator',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'credit.assess',
    description: 'Credit assessment, FOIR calculation, and recommendation handover desk',
  },
  {
    key: 'underwriting-queue',
    label: 'Underwriting Queue',
    href: '/underwriting-queue',
    iconName: 'ClipboardCheck',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'underwriting.view',
    description: 'Manual credit underwriting decision queue and deviation assessment',
  },
  {
    key: 'underwriting',
    label: 'Underwriting',
    href: '/underwriting',
    iconName: 'FileCheck',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'underwriting.view',
    description: 'Consolidated credit underwriting application decision workspace',
  },
  {
    key: 'offers',
    label: 'Offers & Decisions',
    href: '/offers',
    iconName: 'Sparkles',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'offer.view',
    description: 'Loan offers, sanction terms, and Key Fact Statements',
  },
  {
    key: 'documents',
    label: 'Documents',
    href: '/documents',
    iconName: 'FileCheck',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'application.view',
    description: 'Document review, verification, and checklist fulfillment',
  },
  {
    key: 'verifications',
    label: 'Verifications',
    href: '/verifications',
    iconName: 'UserCheck',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'customer.kyc',
    description: 'Identity KYC, bank statement, and bureau verification evidence checks',
  },
  {
    key: 'tasks',
    label: 'Tasks',
    href: '/tasks',
    iconName: 'Clock',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    requiredPermission: 'application.view',
    description: 'Assessment tasks and pending action items',
  },
  {
    key: 'support',
    label: 'Support',
    href: '/support',
    iconName: 'Headphones',
    workspace: 'CREDIT',
    group: 'OVERVIEW',
    description: 'Internal support, customer queries, and communications',
  },

  // ─── HUB 3: FINANCE & SERVICING ───
  {
    key: 'loans',
    label: 'Loan Accounts & Servicing',
    href: '/loans',
    iconName: 'DollarSign',
    workspace: 'FINANCE',
    group: 'SERVICING',
    requiredPermission: 'loan.view',
    description: 'Active loan portfolio, repayment schedules, interest accruals, and statement generation',
  },
  {
    key: 'finance-queue',
    label: 'Finance Queue',
    href: '/finance-queue',
    iconName: 'Coins',
    workspace: 'FINANCE',
    group: 'FINANCIAL_OPS',
    requiredPermission: 'disbursement.view',
    description: 'Pre-disbursement work queue, dual-control validation, bank verification, and payout authorization',
  },
  {
    key: 'disbursements',
    label: 'Disbursements (10-Point Gate)',
    href: '/disbursements',
    iconName: 'Wallet',
    workspace: 'FINANCE',
    group: 'FINANCIAL_OPS',
    requiredPermission: 'disbursement.view',
    description: 'Statutory 10-point pre-payout gatekeeper, penny drop validation, and IMPS/NEFT releases',
  },
  {
    key: 'payments',
    label: 'Payments & Waterfall Ledger',
    href: '/payments',
    iconName: 'Receipt',
    workspace: 'FINANCE',
    group: 'FINANCIAL_OPS',
    requiredPermission: 'payment.view',
    description: 'Repayment transaction ledger with strict Fees -> Penalty -> Interest -> Principal waterfall',
  },
  {
    key: 'general-ledger',
    label: 'General Ledger (Double-Entry)',
    href: '/general-ledger',
    iconName: 'Scale',
    workspace: 'FINANCE',
    group: 'FINANCIAL_OPS',
    requiredPermission: 'finance.gl.view',
    description: 'Chart of Accounts, journal entry balance auditing, trial balance, and financial reports',
  },
  {
    key: 'reconciliation',
    label: 'Automated Recon & Settlements',
    href: '/reconciliation',
    iconName: 'CheckCircle2',
    workspace: 'FINANCE',
    group: 'FINANCIAL_OPS',
    requiredPermission: 'finance.recon.view',
    description: 'Bank statement vs gateway vs internal ledger automated multi-pillar reconciliation',
  },

  // ─── HUB 4: COLLECTIONS & RECOVERY ───
  {
    key: 'collections',
    label: 'Collections & DPD Queues',
    href: '/collections',
    iconName: 'AlertCircle',
    workspace: 'COLLECTIONS',
    group: 'COLLECTIONS',
    requiredPermission: 'collection.view',
    description: 'Delinquency tracking, SMA-0/1/2 DPD aging buckets, collector queues, and PTP logging',
  },
  {
    key: 'npa-monitoring',
    label: 'NPA & Asset Quality',
    href: '/npa-monitoring',
    iconName: 'AlertTriangle',
    workspace: 'COLLECTIONS',
    group: 'COLLECTIONS',
    requiredPermission: 'finance.npa.view',
    description: '90+ DPD Non-Performing Asset monitoring, provisioning, and loss categorization',
  },

  // ─── HUB 5: PARTNER & EMBEDDED LENDING ───
  {
    key: 'partners',
    label: 'Partners, DSAs & Co-Lending',
    href: '/partners',
    iconName: 'Handshake',
    workspace: 'PARTNER',
    group: 'PARTNERSHIP',
    requiredPermission: 'partner.view',
    description: 'Partner directory, LSP agreements, payout commission structures, and sourcing performance',
  },
  {
    key: 'partner-portal',
    label: 'Partner Sourcing Desk',
    href: '/partner',
    iconName: 'Handshake',
    workspace: 'PARTNER',
    group: 'PARTNERSHIP',
    requiredPermission: 'partner.view',
    description: 'Partner application tracking, customer pipeline, API credentials, webhooks, and analytics',
  },

  // ─── HUB 6: CUSTOMER & SUPPORT ───
  {
    key: 'communications',
    label: 'Omnichannel & DLT Hub',
    href: '/communications',
    iconName: 'Mail',
    workspace: 'SUPPORT',
    group: 'SUPPORT',
    requiredPermission: 'communications.view',
    description: 'SMS, WhatsApp, Email, push notifications, TRAI DLT template registry, and quiet hours',
  },
  {
    key: 'support-sla',
    label: 'Support Tickets & Grievances',
    href: '/support-sla',
    iconName: 'LifeBuoy',
    workspace: 'SUPPORT',
    group: 'SUPPORT',
    requiredPermission: 'support.ticket.view',
    description: 'Borrower customer support tickets, 30-day escalation hierarchy, and Nodal Officer desk',
  },

  // ─── HUB 7: PLATFORM & GOVERNANCE ───
  {
    key: 'command-center',
    label: 'AI Command Center',
    href: '/command-center',
    iconName: 'Cpu',
    workspace: 'PLATFORM',
    group: 'GOVERNANCE',
    requiredPermission: 'analytics.command_center',
    description: 'Executive telemetry, portfolio health, daily disbursement velocity, and risk monitors',
  },
  {
    key: 'analytics',
    label: 'Analytics & Intelligence Hub',
    href: '/analytics',
    iconName: 'BarChart3',
    workspace: 'PLATFORM',
    group: 'GOVERNANCE',
    requiredPermission: 'analytics.view',
    description: 'Origination funnel, credit BRE, portfolio risk, DPD delinquency, and executive MIS',
  },
  {
    key: 'reports',
    label: 'Reports & MIS Builder',
    href: '/reports',
    iconName: 'FileSpreadsheet',
    workspace: 'PLATFORM',
    group: 'GOVERNANCE',
    requiredPermission: 'reports.view',
    description: 'Ad-hoc report builder, saved queries, and automated exports',
  },
  {
    key: 'compliance',
    label: 'Regulatory Compliance & DPDP',
    href: '/compliance',
    iconName: 'ShieldCheck',
    workspace: 'PLATFORM',
    group: 'GOVERNANCE',
    requiredPermission: 'compliance.view',
    description: 'RBI digital lending audits, DPDP consent registry, and immutable security audit logs',
  },
  {
    key: 'tenants',
    label: 'Multi-Tenant Institutions',
    href: '/tenants',
    iconName: 'Building2',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'tenant.view',
    description: 'Enterprise B2B tenant onboarding, readiness evaluation, and directory',
  },
  {
    key: 'branches',
    label: 'Branch Directory',
    href: '/branches',
    iconName: 'Building2',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'branch.view',
    description: 'Branch hierarchy, operational geography, IFSC codes, and staff assignments',
  },
  {
    key: 'users',
    label: 'Staff Users & Access',
    href: '/users',
    iconName: 'KeyRound',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'user.view',
    description: 'Internal staff provisioning, branch assignment, and active sessions',
  },
  {
    key: 'roles',
    label: 'Roles & Normalized RBAC',
    href: '/roles',
    iconName: 'ShieldCheck',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'role.view',
    description: 'Role-permission matrix, 8 canonical operational role families, and SoD invariants',
  },
  {
    key: 'workflows',
    label: 'Workflow Studio',
    href: '/workflows',
    iconName: 'Workflow',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'workflow.view',
    description: 'State machine orchestration, stage gates, transition rules, and automated event triggers',
  },
  {
    key: 'bre-studio',
    label: 'BRE & Policy Studio',
    href: '/bre-studio',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'bre.view',
    description: 'Business Rule Engine: credit rules, cutoff thresholds, risk scorecards, and pricing',
  },
  {
    key: 'authority-matrix',
    label: 'Authority & Sanction Matrix',
    href: '/authority-matrix',
    iconName: 'ShieldCheck',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'authority.view',
    description: 'Tiered credit sanction limits, approval authority matrix, and escalation delegations',
  },
  {
    key: 'integrations',
    label: '12-Domain Sandbox Hub',
    href: '/integrations',
    iconName: 'Cpu',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'integration.view',
    description: 'KYC, Bureau, AA, eSign, Mandate, Payment, and SMS deterministic sandbox adapter registry',
  },
  {
    key: 'branding',
    label: 'White-Label Branding',
    href: '/branding',
    iconName: 'Palette',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'branding.view',
    description: 'Custom lender logo, hex color themes, domain masking, and customer portal styling',
  },
  {
    key: 'audit-logs',
    label: 'Immutable Audit Trail',
    href: '/audit-logs',
    iconName: 'ScrollText',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'audit.view',
    description: 'Cryptographically sealed audit trail with actor attribution, tenant scope, and timestamp',
  },
  {
    key: 'settings',
    label: 'System Configuration',
    href: '/settings',
    iconName: 'Sliders',
    workspace: 'PLATFORM',
    group: 'ADMINISTRATION',
    requiredPermission: 'settings.manage',
    description: 'General system settings, security policies, and environment parameters',
  },

  // ─── HUB 8: BORROWER SELF-SERVICE PORTAL ───
  {
    key: 'customer-dashboard',
    label: 'Borrower Overview',
    href: '/customer/dashboard',
    iconName: 'LayoutDashboard',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-apply',
    label: 'Apply for Loan',
    href: '/customer/apply',
    iconName: 'FileText',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-credit',
    label: 'Credit Line & Limits',
    href: '/customer/credit',
    iconName: 'CreditCard',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-documents',
    label: 'My Documents & KYC',
    href: '/customer/documents',
    iconName: 'FileCheck',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-loans',
    label: 'Active Loans & Statements',
    href: '/customer/loan',
    iconName: 'DollarSign',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-payments',
    label: 'Repayments & Pre-closure',
    href: '/customer/payments',
    iconName: 'Receipt',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
  {
    key: 'customer-support',
    label: 'Help & Grievances',
    href: '/customer/support',
    iconName: 'Headphones',
    workspace: 'BORROWER',
    group: 'OVERVIEW',
  },
];
