/**
 * Phase 16: Master Institutional Workspaces, Portals & Navigation Configuration
 */

import {
  PortalKey,
  DepartmentKey,
  WorkspaceKey,
  PortalDefinition,
  WorkspaceDefinition,
  NavigationItemModel,
  FeatureFlagConfig,
} from './workspace.types';

// 1. Master Portals Registry
export const MASTER_PORTALS: Record<PortalKey, PortalDefinition> = {
  PUBLIC: {
    key: 'PUBLIC',
    name: 'Public Portal',
    description: 'Public lending marketing, borrower discovery, and authentication portal',
    iconName: 'Globe',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['*'],
    isEnabled: true,
  },
  OPERATIONS: {
    key: 'OPERATIONS',
    name: 'Operations Portal',
    description: 'Loan origination, onboarding, application processing, and branch workflows',
    iconName: 'Activity',
    defaultWorkspace: 'OPERATIONS_LENDING',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'BRANCH_MANAGER', 'OPERATIONS_MANAGER'],
    isEnabled: true,
  },
  CREDIT: {
    key: 'CREDIT',
    name: 'Credit & Underwriting Portal',
    description: 'Credit assessment, risk scoring, underwriting queues, and credit facilities',
    iconName: 'Calculator',
    defaultWorkspace: 'CREDIT_ASSESSMENT',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER', 'RISK_ANALYST', 'RISK_MANAGER'],
    isEnabled: true,
  },
  COLLECTIONS: {
    key: 'COLLECTIONS',
    name: 'Collections & Recovery Portal',
    description: 'Overdue delinquency aging, promise-to-pay tracking, and legal recovery',
    iconName: 'AlertCircle',
    defaultWorkspace: 'COLLECTIONS_DELINQUENCY',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    isEnabled: true,
  },
  FINANCE: {
    key: 'FINANCE',
    name: 'Finance & Accounting Portal',
    description: 'General ledger, payments ledger, bank reconciliation, treasury and payouts',
    iconName: 'Scale',
    defaultWorkspace: 'FINANCE_GL',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER', 'TREASURY_MANAGER'],
    isEnabled: true,
  },
  MANAGEMENT: {
    key: 'MANAGEMENT',
    name: 'Management & Analytics Portal',
    description: 'Executive command center, MIS reporting, portfolio analytics, and SLA telemetry',
    iconName: 'Cpu',
    defaultWorkspace: 'MANAGEMENT_COMMAND_CENTER',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'RISK_MANAGER', 'EXECUTIVE'],
    isEnabled: true,
  },
  SYSTEM_ADMIN: {
    key: 'SYSTEM_ADMIN',
    name: 'System Admin Portal',
    description: 'Institutional settings, user roles, branches, tenant configs, and system health',
    iconName: 'ShieldCheck',
    defaultWorkspace: 'SYSTEM_ADMIN_WORKSPACE',
    allowedRoles: ['SUPER_ADMIN', 'SYSTEM_ADMIN'],
    isEnabled: true,
  },
  BORROWER: {
    key: 'BORROWER',
    name: 'Borrower Digital Portal',
    description: 'Direct-to-consumer digital borrowing, KFS acceptance, and loan servicing',
    iconName: 'User',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  PARTNER: {
    key: 'PARTNER',
    name: 'Partner & LSP Portal',
    description: 'Embedded lending gateway, partner applications, webhooks, and credentials',
    iconName: 'Handshake',
    defaultWorkspace: 'PARTNER_EMBEDDED_HUB',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'SYSTEM_ADMIN'],
    isEnabled: true,
  },
  AUDITOR: {
    key: 'AUDITOR',
    name: 'Audit & Governance Portal',
    description: 'Read-only independent inspection, trace, and audit verification',
    iconName: 'ShieldCheck',
    defaultWorkspace: 'AUDITOR_GOVERNANCE',
    allowedRoles: ['AUDITOR', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  RISK_FRAUD: {
    key: 'RISK_FRAUD',
    name: 'Risk & Fraud Manager Portal',
    description: 'Fraud monitoring, investigations, risk alerts, and control mechanisms',
    iconName: 'ShieldAlert',
    defaultWorkspace: 'RISK_FRAUD_WORKSPACE',
    allowedRoles: ['RISK_FRAUD_MANAGER', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  FRAUD_INVESTIGATOR: {
    key: 'FRAUD_INVESTIGATOR',
    name: 'Fraud Investigator Portal',
    description: 'Investigation queue, evidence collection, and fraud case management',
    iconName: 'Search',
    defaultWorkspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    allowedRoles: ['FRAUD_INVESTIGATOR', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  RISK_ANALYST: {
    key: 'RISK_ANALYST',
    name: 'Risk Analyst Portal',
    description: 'Risk assessment, policy exceptions, portfolio risk, and recommendations',
    iconName: 'Activity',
    defaultWorkspace: 'RISK_ANALYST_WORKSPACE',
    allowedRoles: ['RISK_ANALYST', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  BRANCH_MANAGER: {
    key: 'BRANCH_MANAGER',
    name: 'Branch Manager Portal',
    description: 'Branch-level operational oversight, management review, and team performance',
    iconName: 'Building',
    defaultWorkspace: 'BRANCH_MANAGER_WORKSPACE',
    allowedRoles: ['BRANCH_MANAGER', 'SUPER_ADMIN'],
    isEnabled: true,
  },
};

// 2. Master Workspaces Registry
export const MASTER_WORKSPACES: Record<WorkspaceKey, WorkspaceDefinition> = {
  // OPERATIONS PORTAL WORKSPACES
  OPERATIONS_LENDING: {
    key: 'OPERATIONS_LENDING',
    name: 'Lending Operations',
    shortLabel: 'Lending Ops',
    description: 'Loan origination, applicant queue, application tracking, and servicing',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'FileText',
    defaultRoute: '/dashboard',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'OPERATIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  OPERATIONS_BRANCH: {
    key: 'OPERATIONS_BRANCH',
    name: 'Branch Management Desk',
    shortLabel: 'Branch Desk',
    description: 'Branch proposal reviews, staff oversight, and delegated sanction limits',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Building2',
    defaultRoute: '/branch-review',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  OPERATIONS_ONBOARDING: {
    key: 'OPERATIONS_ONBOARDING',
    name: 'Customer Onboarding',
    shortLabel: 'Onboarding',
    description: 'Customer directory, KYC verification desk, and document management',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Users',
    defaultRoute: '/customers',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // CREDIT PORTAL WORKSPACES
  CREDIT_ASSESSMENT: {
    key: 'CREDIT_ASSESSMENT',
    name: 'Credit Assessment Desk',
    shortLabel: 'Credit Desk',
    description: 'Financial capacity analysis, FOIR calculation, and credit recommendations',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'Calculator',
    defaultRoute: '/credit-assessment',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  CREDIT_UNDERWRITING: {
    key: 'CREDIT_UNDERWRITING',
    name: 'Underwriting & Sanctions',
    shortLabel: 'Underwriting',
    description: 'Final sanction decisions, policy exception approvals, and authority matrix',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'FileCheck',
    defaultRoute: '/underwriting',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'UNDERWRITER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },


  // COLLECTIONS PORTAL WORKSPACES
  COLLECTIONS_DELINQUENCY: {
    key: 'COLLECTIONS_DELINQUENCY',
    name: 'Delinquency & DPD Aging',
    shortLabel: 'Delinquency',
    description: 'Overdue case queues, collector assignment, and Promise-to-Pay (PTP) logs',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertCircle',
    defaultRoute: '/collections/dashboard',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  COLLECTIONS_RECOVERY: {
    key: 'COLLECTIONS_RECOVERY',
    name: 'Recovery & NPA Monitoring',
    shortLabel: 'NPA Recovery',
    description: 'NPA asset quality tracking, early warning triggers, and legal notices',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertTriangle',
    defaultRoute: '/npa-monitoring',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  COLLECTIONS_SETTLEMENTS: {
    key: 'COLLECTIONS_SETTLEMENTS',
    name: 'Settlements & Debt Relief',
    shortLabel: 'Settlements',
    description: 'One-Time Settlement (OTS) requests, penalty waivers, and loan restructuring',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'Scale',
    defaultRoute: '/settlements',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // FINANCE PORTAL WORKSPACES
  FINANCE_GL: {
    key: 'FINANCE_GL',
    name: 'General Ledger (GL)',
    shortLabel: 'General Ledger',
    description: 'Double-entry trial balance, chart of accounts, and financial MIS statements',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Scale',
    defaultRoute: '/general-ledger',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  FINANCE_TREASURY: {
    key: 'FINANCE_TREASURY',
    name: 'Treasury & Disbursements',
    shortLabel: 'Treasury',
    description: 'Disbursement batch maker-checker, payout execution, and repayment receipts',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Wallet',
    defaultRoute: '/disbursements',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  FINANCE_RECONCILIATION: {
    key: 'FINANCE_RECONCILIATION',
    name: 'Banking & Reconciliation',
    shortLabel: 'Reconciliation',
    description: 'Bank statement 3-way matching, payment gateway settlements, and float audit',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Receipt',
    defaultRoute: '/reconciliation',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // MANAGEMENT PORTAL WORKSPACES
  MANAGEMENT_COMMAND_CENTER: {
    key: 'MANAGEMENT_COMMAND_CENTER',
    name: 'Executive Command Center',
    shortLabel: 'Command Center',
    description: 'Centralized executive operational health, AI telemetry, and portfolio KPI radar',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'Cpu',
    defaultRoute: '/command-center',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'EXECUTIVE'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  MANAGEMENT_ANALYTICS: {
    key: 'MANAGEMENT_ANALYTICS',
    name: 'Portfolio Analytics & MIS',
    shortLabel: 'Analytics',
    description: 'Origination funnel, 2D risk-fraud matrices, collector productivity, and custom reports',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'BarChart3',
    defaultRoute: '/analytics',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  MANAGEMENT_EARLY_WARNINGS: {
    key: 'MANAGEMENT_EARLY_WARNINGS',
    name: 'Early Warning Center',
    shortLabel: 'Early Warnings',
    description: 'Pre-delinquency telemetry, bureau degradation alerts, and liquidity forecast',
    portal: 'MANAGEMENT',
    department: 'RISK',
    iconName: 'AlertTriangle',
    defaultRoute: '/early-warnings',
    allowedRoles: ['SUPER_ADMIN', 'COMPANY_ADMIN', 'RISK_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // SYSTEM ADMIN WORKSPACE
  SYSTEM_ADMIN_WORKSPACE: {
    key: 'SYSTEM_ADMIN_WORKSPACE',
    name: 'System Admin Desk',
    shortLabel: 'System Admin',
    description: 'User management, configuration, platform health, and audit logs',
    portal: 'SYSTEM_ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'ShieldCheck',
    defaultRoute: '/system-admin/dashboard',
    allowedRoles: ['SUPER_ADMIN', 'SYSTEM_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },

  // AUDITOR WORKSPACE
  AUDITOR_GOVERNANCE: {
    key: 'AUDITOR_GOVERNANCE',
    name: 'Audit & Governance',
    shortLabel: 'Auditor',
    description: 'Read-only inspection, trace, and audit verification',
    portal: 'AUDITOR',
    department: 'COMPLIANCE',
    iconName: 'ShieldCheck',
    defaultRoute: '/auditor/dashboard',
    allowedRoles: ['AUDITOR', 'SUPER_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  
  // RISK & FRAUD WORKSPACE
  RISK_FRAUD_WORKSPACE: {
    key: 'RISK_FRAUD_WORKSPACE',
    name: 'Risk & Fraud Investigation Desk',
    shortLabel: 'Risk & Fraud',
    description: 'Fraud monitoring, investigations, risk alerts, and control mechanisms',
    portal: 'RISK_FRAUD',
    department: 'RISK',
    iconName: 'ShieldAlert',
    defaultRoute: '/risk-fraud/dashboard',
    allowedRoles: ['RISK_FRAUD_MANAGER', 'SUPER_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  
  // FRAUD INVESTIGATOR WORKSPACE
  FRAUD_INVESTIGATOR_WORKSPACE: {
    key: 'FRAUD_INVESTIGATOR_WORKSPACE',
    name: 'Fraud Investigation Desk',
    shortLabel: 'Investigations',
    description: 'Investigation queue, evidence collection, and fraud case management',
    portal: 'FRAUD_INVESTIGATOR',
    department: 'RISK',
    iconName: 'Search',
    defaultRoute: '/fraud-investigator/dashboard',
    allowedRoles: ['FRAUD_INVESTIGATOR', 'SUPER_ADMIN'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  
  // RISK ANALYST WORKSPACE
  RISK_ANALYST_WORKSPACE: {
    key: 'RISK_ANALYST_WORKSPACE',
    name: 'Risk Analyst Desk',
    shortLabel: 'Risk Analyst',
    description: 'Risk assessment, policy exceptions, portfolio risk, and recommendations',
    portal: 'RISK_ANALYST',
    department: 'RISK',
    iconName: 'Activity',
    defaultRoute: '/risk-analyst/dashboard',
    allowedRoles: ['RISK_ANALYST', 'SUPER_ADMIN'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  
  // BRANCH MANAGER WORKSPACE
  BRANCH_MANAGER_WORKSPACE: {
    key: 'BRANCH_MANAGER_WORKSPACE',
    name: 'Branch Manager Desk',
    shortLabel: 'Branch Manager',
    description: 'Branch-level operational oversight, management review, and team performance',
    portal: 'BRANCH_MANAGER',
    department: 'OPERATIONS',
    iconName: 'Building',
    defaultRoute: '/branch-manager/dashboard',
    allowedRoles: ['BRANCH_MANAGER', 'SUPER_ADMIN'],
    displayOrder: 4,
    status: 'ACTIVE',
  },

  // BORROWER WORKSPACE
  BORROWER_SELF_SERVICE: {
    key: 'BORROWER_SELF_SERVICE',
    name: 'Borrower Self-Service Hub',
    shortLabel: 'My Account',
    description: 'Customer application status, KFS acceptance, repayments, and NOC certificates',
    portal: 'BORROWER',
    department: 'CUSTOMER_SERVICE',
    iconName: 'User',
    defaultRoute: '/borrower',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },

  // PARTNER WORKSPACE
  PARTNER_EMBEDDED_HUB: {
    key: 'PARTNER_EMBEDDED_HUB',
    name: 'Partner / LSP Embedded Desk',
    shortLabel: 'Partner Hub',
    description: 'Embedded loan origination pipeline, DSA agents, API keys, and webhook logs',
    portal: 'PARTNER',
    department: 'PARTNER_NETWORK',
    iconName: 'Handshake',
    defaultRoute: '/partner',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'SYSTEM_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
};

// 3. Master Navigation Hierarchy Tree
export const MASTER_NAVIGATION: NavigationItemModel[] = [
  // --- OPERATIONS / LENDING ---
  {
    id: 'nav-ops-dashboard',
    label: 'Operations Dashboard',
    icon: 'LayoutDashboard',
    route: '/dashboard',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-ops-apps',
    label: 'Loan Applications',
    icon: 'FileText',
    route: '/applications',
    permission: 'application.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-ops-returned',
    label: 'Returned Applications',
    icon: 'RotateCcw',
    route: '/returned-applications',
    permission: 'application.return',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-ops-loans',
    label: 'Active Loan Accounts',
    icon: 'DollarSign',
    route: '/loans',
    permission: 'loan.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-ops-customers',
    label: 'Customer 360 Directory',
    icon: 'Users',
    route: '/customers',
    permission: 'customer.view',
    workspace: 'OPERATIONS_ONBOARDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-ops-branch-review',
    label: 'Branch Applications Desk',
    icon: 'Building2',
    route: '/branch-review',
    permission: 'approval.view',
    workspace: 'OPERATIONS_BRANCH',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-ops-comms',
    label: 'Omnichannel Communications',
    icon: 'Mail',
    route: '/communications',
    permission: 'communication.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 7,
    enabled: true,
  },

  // --- CREDIT & RISK ---
  {
    id: 'nav-credit-desk',
    label: 'Credit Assessment Desk',
    icon: 'Calculator',
    route: '/credit-assessment',
    permission: 'credit.assess',
    workspace: 'CREDIT_ASSESSMENT',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-credit-underwriting',
    label: 'Underwriting Queue',
    icon: 'FileCheck',
    route: '/underwriting',
    permission: 'underwriting.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-credit-approval-queue',
    label: 'Approval Authority Queue',
    icon: 'ShieldCheck',
    route: '/approval-queue',
    permission: 'approval.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-credit-facilities',
    label: 'Credit Facilities & Limits',
    icon: 'Layers',
    route: '/credit-facilities',
    permission: 'credit_limit.view',
    workspace: 'CREDIT_ASSESSMENT',
    portal: 'CREDIT',
    group: 'OPERATIONS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-credit-offers',
    label: 'Offer Engine & KFS',
    icon: 'Receipt',
    route: '/offers',
    permission: 'offer.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'OPERATIONS',
    displayOrder: 5,
    enabled: true,
  },

  // --- COLLECTIONS & RECOVERY ---
  {
    id: 'nav-coll-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/collections/dashboard',
    permission: 'collection.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-coll-queue',
    label: 'Collection Queue',
    icon: 'List',
    route: '/collections/queue',
    permission: 'collection.queue.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-coll-my-accounts',
    label: 'My Accounts',
    icon: 'Briefcase',
    route: '/collections/my-accounts',
    permission: 'collection.account.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-coll-due',
    label: 'Due & Overdue',
    icon: 'AlertCircle',
    route: '/collections/due-overdue',
    permission: 'collection.account.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-coll-ptp',
    label: 'Promise to Pay',
    icon: 'Calendar',
    route: '/collections/promise-to-pay',
    permission: 'collection.promise.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-coll-activities',
    label: 'Collection Activities',
    icon: 'Activity',
    route: '/collections/activities',
    permission: 'collection.activity.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-coll-payments',
    label: 'Payments',
    icon: 'DollarSign',
    route: '/collections/payments',
    permission: 'collection.payment.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-coll-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/collections/customers',
    permission: 'customer.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-coll-tasks',
    label: 'Tasks',
    icon: 'CheckSquare',
    route: '/collections/tasks',
    permission: 'task.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-coll-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/collections/reports',
    permission: 'report.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 10,
    enabled: true,
  },
  {
    id: 'nav-coll-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/collections/support',
    permission: 'support.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 11,
    enabled: true,
  },

  // --- FINANCE & ACCOUNTING ---
  {
    id: 'nav-fin-gl',
    label: 'General Ledger (GL)',
    icon: 'Scale',
    route: '/general-ledger',
    permission: 'accounting.view',
    workspace: 'FINANCE_GL',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-fin-disbursements',
    label: 'Disbursement Batches',
    icon: 'Wallet',
    route: '/disbursements',
    permission: 'disbursement.view',
    workspace: 'FINANCE_TREASURY',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-fin-payments',
    label: 'Payments & Collections Ledger',
    icon: 'Receipt',
    route: '/payments',
    permission: 'payment.view',
    workspace: 'FINANCE_TREASURY',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-fin-recon',
    label: 'Banking & Reconciliation',
    icon: 'Scale',
    route: '/reconciliation',
    permission: 'reconciliation.view',
    workspace: 'FINANCE_RECONCILIATION',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 4,
    enabled: true,
  },

  // --- MANAGEMENT & ANALYTICS ---
  {
    id: 'nav-mgmt-cmd',
    label: 'Executive Command Center',
    icon: 'Cpu',
    route: '/command-center',
    permission: 'analytics.command_center',
    workspace: 'MANAGEMENT_COMMAND_CENTER',
    portal: 'MANAGEMENT',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-mgmt-analytics',
    label: 'Portfolio Analytics Hub',
    icon: 'BarChart3',
    route: '/analytics',
    permission: 'analytics.view',
    workspace: 'MANAGEMENT_ANALYTICS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-mgmt-reports',
    label: 'MIS Reports & Exports',
    icon: 'FileText',
    route: '/reports',
    permission: 'report.view',
    workspace: 'MANAGEMENT_ANALYTICS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-mgmt-early-warnings',
    label: 'Early Warnings Center',
    icon: 'AlertTriangle',
    route: '/early-warnings',
    permission: 'risk.view',
    workspace: 'MANAGEMENT_EARLY_WARNINGS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-mgmt-operations',
    label: 'Operations Observability',
    icon: 'Activity',
    route: '/operations',
    permission: 'operations.view',
    workspace: 'MANAGEMENT_COMMAND_CENTER',
    portal: 'MANAGEMENT',
    group: 'OVERVIEW',
    displayOrder: 5,
    enabled: true,
  },

  // --- SYSTEM ADMIN ---
  {
    id: 'nav-sys-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/system-admin/dashboard',
    permission: 'tenant.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-sys-users',
    label: 'Users',
    icon: 'Users',
    route: '/system-admin/users',
    permission: 'user.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-sys-roles',
    label: 'Roles & Permissions',
    icon: 'ShieldCheck',
    route: '/system-admin/roles-permissions',
    permission: 'role.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-sys-branches',
    label: 'Branches',
    icon: 'Building2',
    route: '/system-admin/branches',
    permission: 'branch.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-sys-tenants',
    label: 'Tenants',
    icon: 'Layers',
    route: '/system-admin/tenants',
    permission: 'tenant.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-sys-config',
    label: 'System Configuration',
    icon: 'Sliders',
    route: '/system-admin/system-configuration',
    permission: 'config.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-sys-integrations',
    label: 'Integrations',
    icon: 'Link',
    route: '/system-admin/integrations',
    permission: 'integration.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-sys-health',
    label: 'Platform Health',
    icon: 'Activity',
    route: '/system-admin/platform-health',
    permission: 'system.observability',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-sys-audit',
    label: 'Audit Logs',
    icon: 'FileText',
    route: '/system-admin/audit-logs',
    permission: 'audit.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-sys-tasks',
    label: 'Admin Tasks',
    icon: 'CheckSquare',
    route: '/system-admin/admin-tasks',
    permission: 'user.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 10,
    enabled: true,
  },
  {
    id: 'nav-sys-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/system-admin/reports',
    permission: 'reports.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 11,
    enabled: true,
  },
  {
    id: 'nav-sys-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/system-admin/support',
    permission: 'support.view',
    workspace: 'SYSTEM_ADMIN_WORKSPACE',
    portal: 'SYSTEM_ADMIN',
    group: 'SETTINGS',
    displayOrder: 12,
    enabled: true,
  },
  // --- AUDITOR / GOVERNANCE ---
  {
    id: 'nav-auditor-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/auditor/dashboard',
    permission: 'audit.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-auditor-applications',
    label: 'Applications',
    icon: 'FileText',
    route: '/auditor/applications',
    permission: 'application.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-auditor-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/auditor/customers',
    permission: 'customer.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-auditor-loans',
    label: 'Loans',
    icon: 'DollarSign',
    route: '/auditor/loans',
    permission: 'loan.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-auditor-financial-audit',
    label: 'Financial Audit',
    icon: 'Scale',
    route: '/auditor/financial-audit',
    permission: 'finance.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-auditor-underwriting-audit',
    label: 'Underwriting Audit',
    icon: 'FileCheck',
    route: '/auditor/underwriting-audit',
    permission: 'underwriting.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-auditor-partner-audit',
    label: 'Partner Audit',
    icon: 'Handshake',
    route: '/auditor/partner-audit',
    permission: 'partner.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-auditor-audit-logs',
    label: 'Audit Logs',
    icon: 'ScrollText',
    route: '/auditor/audit-logs',
    permission: 'audit.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-auditor-reports',
    label: 'Reports',
    icon: 'BarChart3',
    route: '/auditor/reports',
    permission: 'report.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-auditor-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/auditor/support',
    permission: 'support.view',
    workspace: 'AUDITOR_GOVERNANCE',
    portal: 'AUDITOR',
    group: 'OVERVIEW',
    displayOrder: 10,
    enabled: true,
  },

  // --- PARTNERS & EMBEDDED ---
  {
    id: 'nav-partner-desk',
    label: 'Partner Origination Desk',
    icon: 'Handshake',
    route: '/partners',
    permission: 'partner.view',
    workspace: 'PARTNER_EMBEDDED_HUB',
    portal: 'PARTNER',
    group: 'OPERATIONS',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-partner-portal',
    label: 'LSP / Embedded Portal',
    icon: 'Layers',
    route: '/partner',
    permission: 'partner.view',
    workspace: 'PARTNER_EMBEDDED_HUB',
    portal: 'PARTNER',
    group: 'OPERATIONS',
    displayOrder: 2,
    enabled: true,
  },

  // --- BORROWER DIGITAL PORTAL ---
  {
    id: 'nav-borrower-home',
    label: 'Home',
    icon: 'Home',
    route: '/borrower',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-borrower-apps',
    label: 'My Applications',
    icon: 'FileText',
    route: '/borrower/apply',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-borrower-documents',
    label: 'Documents',
    icon: 'FolderOpen',
    route: '/borrower/documents',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-borrower-offers',
    label: 'Offers',
    icon: 'Tag',
    route: '/borrower/offers',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-borrower-loans',
    label: 'My Loans',
    icon: 'CreditCard',
    route: '/borrower/loans',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-borrower-payments',
    label: 'Payments',
    icon: 'Receipt',
    route: '/borrower/payments',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-borrower-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/borrower/support',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-borrower-profile',
    label: 'Profile',
    icon: 'User',
    route: '/borrower/profile',
    workspace: 'BORROWER_SELF_SERVICE',
    portal: 'BORROWER',
    group: 'OVERVIEW',
    displayOrder: 8,
    enabled: true,
  },
  
  // --- RISK & FRAUD ---
  {
    id: 'nav-rf-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/risk-fraud/dashboard',
    permission: 'risk.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-rf-risk-queue',
    label: 'Risk Queue',
    icon: 'List',
    route: '/risk-fraud/risk-queue',
    permission: 'risk.alert.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-rf-fraud-queue',
    label: 'Fraud Queue',
    icon: 'AlertTriangle',
    route: '/risk-fraud/fraud-queue',
    permission: 'fraud.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-rf-applications',
    label: 'Applications',
    icon: 'FileText',
    route: '/risk-fraud/applications',
    permission: 'application.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-rf-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/risk-fraud/customers',
    permission: 'customer.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-rf-fraud-cases',
    label: 'Fraud Cases',
    icon: 'ShieldAlert',
    route: '/risk-fraud/fraud-cases',
    permission: 'fraud.case.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-rf-risk-alerts',
    label: 'Risk Alerts',
    icon: 'AlertCircle',
    route: '/risk-fraud/risk-alerts',
    permission: 'risk.alert.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-rf-investigations',
    label: 'Investigations',
    icon: 'Search',
    route: '/risk-fraud/investigations',
    permission: 'risk.investigation.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-rf-watchlists',
    label: 'Watchlists',
    icon: 'Eye',
    route: '/risk-fraud/watchlists',
    permission: 'watchlist.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-rf-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/risk-fraud/reports',
    permission: 'report.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 10,
    enabled: true,
  },
  {
    id: 'nav-rf-tasks',
    label: 'Tasks',
    icon: 'CheckSquare',
    route: '/risk-fraud/tasks',
    permission: 'task.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 11,
    enabled: true,
  },
  {
    id: 'nav-rf-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/risk-fraud/support',
    permission: 'support.view',
    workspace: 'RISK_FRAUD_WORKSPACE',
    portal: 'RISK_FRAUD',
    group: 'WORKFLOW',
    displayOrder: 12,
    enabled: true,
  },
  
  // --- FRAUD INVESTIGATOR ---
  {
    id: 'nav-fi-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/fraud-investigator/dashboard',
    permission: 'fraud.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-fi-queue',
    label: 'Investigation Queue',
    icon: 'List',
    route: '/fraud-investigator/queue',
    permission: 'fraud.case.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-fi-cases',
    label: 'My Cases',
    icon: 'Folder',
    route: '/fraud-investigator/cases',
    permission: 'fraud.case.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-fi-alerts',
    label: 'Alerts',
    icon: 'AlertTriangle',
    route: '/fraud-investigator/alerts',
    permission: 'fraud.alert.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-fi-applications',
    label: 'Applications',
    icon: 'FileText',
    route: '/fraud-investigator/applications',
    permission: 'application.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-fi-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/fraud-investigator/customers',
    permission: 'customer.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-fi-evidence',
    label: 'Evidence',
    icon: 'Database',
    route: '/fraud-investigator/evidence',
    permission: 'fraud.evidence.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-fi-investigations',
    label: 'Investigations',
    icon: 'Search',
    route: '/fraud-investigator/investigations',
    permission: 'fraud.investigation.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-fi-tasks',
    label: 'Tasks',
    icon: 'CheckSquare',
    route: '/fraud-investigator/tasks',
    permission: 'task.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-fi-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/fraud-investigator/reports',
    permission: 'report.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 10,
    enabled: true,
  },
  {
    id: 'nav-fi-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/fraud-investigator/support',
    permission: 'support.view',
    workspace: 'FRAUD_INVESTIGATOR_WORKSPACE',
    portal: 'FRAUD_INVESTIGATOR',
    group: 'WORKFLOW',
    displayOrder: 11,
    enabled: true,
  },
  
  // --- RISK ANALYST ---
  {
    id: 'nav-ra-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/risk-analyst/dashboard',
    permission: 'risk.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-ra-assessment',
    label: 'Risk Assessment',
    icon: 'Shield',
    route: '/risk-analyst/assessment',
    permission: 'risk.assess',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-ra-queue',
    label: 'Risk Queue',
    icon: 'List',
    route: '/risk-analyst/queue',
    permission: 'risk.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-ra-applications',
    label: 'Applications',
    icon: 'FileText',
    route: '/risk-analyst/applications',
    permission: 'application.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-ra-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/risk-analyst/customers',
    permission: 'customer.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-ra-alerts',
    label: 'Risk Alerts',
    icon: 'AlertTriangle',
    route: '/risk-analyst/alerts',
    permission: 'risk.alert.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-ra-portfolio',
    label: 'Portfolio Risk',
    icon: 'PieChart',
    route: '/risk-analyst/portfolio',
    permission: 'risk.portfolio.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-ra-tasks',
    label: 'Tasks',
    icon: 'CheckSquare',
    route: '/risk-analyst/tasks',
    permission: 'task.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-ra-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/risk-analyst/reports',
    permission: 'report.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-ra-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/risk-analyst/support',
    permission: 'support.view',
    workspace: 'RISK_ANALYST_WORKSPACE',
    portal: 'RISK_ANALYST',
    group: 'WORKFLOW',
    displayOrder: 10,
    enabled: true,
  },
  
  // --- BRANCH MANAGER ---
  {
    id: 'nav-bm-dashboard',
    label: 'Dashboard',
    icon: 'LayoutDashboard',
    route: '/branch-manager/dashboard',
    permission: 'branch.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-bm-applications',
    label: 'Applications',
    icon: 'FileText',
    route: '/branch-manager/applications',
    permission: 'application.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-bm-customers',
    label: 'Customers',
    icon: 'Users',
    route: '/branch-manager/customers',
    permission: 'customer.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-bm-loans',
    label: 'Loans',
    icon: 'Briefcase',
    route: '/branch-manager/loans',
    permission: 'loan.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-bm-tasks',
    label: 'Team & Tasks',
    icon: 'CheckSquare',
    route: '/branch-manager/tasks',
    permission: 'task.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-bm-collections',
    label: 'Collections',
    icon: 'CreditCard',
    route: '/branch-manager/collections',
    permission: 'collection.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-bm-operations',
    label: 'Branch Operations',
    icon: 'Activity',
    route: '/branch-manager/operations',
    permission: 'branch.operations.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-bm-reports',
    label: 'Reports',
    icon: 'BarChart2',
    route: '/branch-manager/reports',
    permission: 'report.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-bm-support',
    label: 'Support',
    icon: 'HelpCircle',
    route: '/branch-manager/support',
    permission: 'support.view',
    workspace: 'BRANCH_MANAGER_WORKSPACE',
    portal: 'BRANCH_MANAGER',
    group: 'WORKFLOW',
    displayOrder: 9,
    enabled: true,
  },
];

// 4. Default Department-to-Workspace Default Mapping
export const ROLE_DEPARTMENT_MAP: Record<string, DepartmentKey> = {
  SUPER_SYSTEM_ADMIN: 'ADMINISTRATION',
  SYSTEM_ADMIN: 'ADMINISTRATION',
  COMPANY_ADMIN: 'MANAGEMENT',
  LOAN_OFFICER: 'OPERATIONS',
  BRANCH_MANAGER: 'OPERATIONS',
  CREDIT_ANALYST: 'CREDIT',
  UNDERWRITER: 'CREDIT',
  RISK_ANALYST: 'RISK',
  RISK_MANAGER: 'RISK',
  FRAUD_ANALYST: 'RISK',
  RISK_FRAUD_MANAGER: 'RISK',
  FRAUD_INVESTIGATOR: 'RISK',
  COLLECTION_OFFICER: 'COLLECTIONS',
  COLLECTIONS_MANAGER: 'COLLECTIONS',
  FINANCE_OFFICER: 'FINANCE',
  AUDITOR: 'COMPLIANCE',
  CUSTOMER: 'CUSTOMER_SERVICE',
  PARTNER: 'PARTNER_NETWORK',
};

// 5. Default Feature Flags
export const DEFAULT_FEATURE_FLAGS: FeatureFlagConfig = {
  enableBreStudio: true,
  enableAiCommandCenter: true,
  enableDigiLockerKyc: true,
  enableInstantEnach: true,
  enableCollectionsAutomation: true,
  enableAdvancedReporting: true,
  enableWhiteLabelBranding: true,
  enableBorrowerApp: true,
  enablePartnerLspPlatform: true,
};
