/**
 * Phase 16: Master Institutional Workspaces, Portals & Navigation Configuration
 */

import {
  PortalKey,
  DepartmentKey,
  WorkspaceKey,
  PortalDefinition,
  WorkspaceDefinition,
  NavigationItemModel,
  FeatureFlagConfig,
} from './workspace.types';

// 1. Master Portals Registry
export const MASTER_PORTALS: Record<PortalKey, PortalDefinition> = {
  PUBLIC: {
    key: 'PUBLIC',
    name: 'Public Portal',
    description: 'Public lending marketing, borrower discovery, and authentication portal',
    iconName: 'Globe',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['*'],
    isEnabled: true,
  },
  OPERATIONS: {
    key: 'OPERATIONS',
    name: 'Operations Portal',
    description: 'Loan origination, onboarding, application processing, and branch workflows',
    iconName: 'Activity',
    defaultWorkspace: 'OPERATIONS_LENDING',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'BRANCH_MANAGER', 'OPERATIONS_MANAGER'],
    isEnabled: true,
  },
  CREDIT: {
    key: 'CREDIT',
    name: 'Credit & Underwriting Portal',
    description: 'Credit assessment, risk scoring, underwriting queues, and credit facilities',
    iconName: 'Calculator',
    defaultWorkspace: 'CREDIT_ASSESSMENT',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER', 'RISK_ANALYST', 'RISK_MANAGER'],
    isEnabled: true,
  },
  COLLECTIONS: {
    key: 'COLLECTIONS',
    name: 'Collections & Recovery Portal',
    description: 'Overdue delinquency aging, promise-to-pay tracking, and legal recovery',
    iconName: 'AlertCircle',
    defaultWorkspace: 'COLLECTIONS_DELINQUENCY',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    isEnabled: true,
  },
  FINANCE: {
    key: 'FINANCE',
    name: 'Finance & Accounting Portal',
    description: 'General ledger, payments ledger, bank reconciliation, treasury and payouts',
    iconName: 'Scale',
    defaultWorkspace: 'FINANCE_GL',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER', 'TREASURY_MANAGER'],
    isEnabled: true,
  },
  MANAGEMENT: {
    key: 'MANAGEMENT',
    name: 'Management & Analytics Portal',
    description: 'Executive command center, MIS reporting, portfolio analytics, and SLA telemetry',
    iconName: 'Cpu',
    defaultWorkspace: 'MANAGEMENT_COMMAND_CENTER',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'RISK_MANAGER', 'EXECUTIVE'],
    isEnabled: true,
  },
  ADMIN: {
    key: 'ADMIN',
    name: 'Administration Portal',
    description: 'Institutional settings, user roles, BRE rule studio, workflows, and audit compliance',
    iconName: 'ShieldCheck',
    defaultWorkspace: 'ADMIN_ACCESS_CONTROL',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'AUDITOR'],
    isEnabled: true,
  },
  BORROWER: {
    key: 'BORROWER',
    name: 'Borrower Digital Portal',
    description: 'Direct-to-consumer digital borrowing, KFS acceptance, and loan servicing',
    iconName: 'User',
    defaultWorkspace: 'BORROWER_SELF_SERVICE',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    isEnabled: true,
  },
  PARTNER: {
    key: 'PARTNER',
    name: 'Partner & LSP Portal',
    description: 'Embedded lending gateway, partner applications, webhooks, and credentials',
    iconName: 'Handshake',
    defaultWorkspace: 'PARTNER_EMBEDDED_HUB',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'ADMIN'],
    isEnabled: true,
  },
};

// 2. Master Workspaces Registry
export const MASTER_WORKSPACES: Record<WorkspaceKey, WorkspaceDefinition> = {
  // OPERATIONS PORTAL WORKSPACES
  OPERATIONS_LENDING: {
    key: 'OPERATIONS_LENDING',
    name: 'Lending Operations',
    shortLabel: 'Lending Ops',
    description: 'Loan origination, applicant queue, application tracking, and servicing',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'FileText',
    defaultRoute: '/dashboard',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER', 'OPERATIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  OPERATIONS_BRANCH: {
    key: 'OPERATIONS_BRANCH',
    name: 'Branch Management Desk',
    shortLabel: 'Branch Desk',
    description: 'Branch proposal reviews, staff oversight, and delegated sanction limits',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Building2',
    defaultRoute: '/branch-review',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  OPERATIONS_ONBOARDING: {
    key: 'OPERATIONS_ONBOARDING',
    name: 'Customer Onboarding',
    shortLabel: 'Onboarding',
    description: 'Customer directory, KYC verification desk, and document management',
    portal: 'OPERATIONS',
    department: 'OPERATIONS',
    iconName: 'Users',
    defaultRoute: '/customers',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'LOAN_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // CREDIT PORTAL WORKSPACES
  CREDIT_ASSESSMENT: {
    key: 'CREDIT_ASSESSMENT',
    name: 'Credit Assessment Desk',
    shortLabel: 'Credit Desk',
    description: 'Financial capacity analysis, FOIR calculation, and credit recommendations',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'Calculator',
    defaultRoute: '/credit-assessment',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'CREDIT_ANALYST', 'UNDERWRITER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  CREDIT_UNDERWRITING: {
    key: 'CREDIT_UNDERWRITING',
    name: 'Underwriting & Sanctions',
    shortLabel: 'Underwriting',
    description: 'Final sanction decisions, policy exception approvals, and authority matrix',
    portal: 'CREDIT',
    department: 'CREDIT',
    iconName: 'FileCheck',
    defaultRoute: '/underwriting',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'UNDERWRITER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  CREDIT_RISK_STUDIO: {
    key: 'CREDIT_RISK_STUDIO',
    name: 'Risk & Fraud Intelligence',
    shortLabel: 'Risk Studio',
    description: '6-pillar risk scoring, fraud graph visualization, and credit facility rules',
    portal: 'CREDIT',
    department: 'RISK',
    iconName: 'ShieldAlert',
    defaultRoute: '/risk',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'RISK_ANALYST', 'RISK_MANAGER', 'FRAUD_ANALYST'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // COLLECTIONS PORTAL WORKSPACES
  COLLECTIONS_DELINQUENCY: {
    key: 'COLLECTIONS_DELINQUENCY',
    name: 'Delinquency & DPD Aging',
    shortLabel: 'Delinquency',
    description: 'Overdue case queues, collector assignment, and Promise-to-Pay (PTP) logs',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertCircle',
    defaultRoute: '/collections',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTION_OFFICER', 'COLLECTIONS_MANAGER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  COLLECTIONS_RECOVERY: {
    key: 'COLLECTIONS_RECOVERY',
    name: 'Recovery & NPA Monitoring',
    shortLabel: 'NPA Recovery',
    description: 'NPA asset quality tracking, early warning triggers, and legal notices',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'AlertTriangle',
    defaultRoute: '/npa-monitoring',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  COLLECTIONS_SETTLEMENTS: {
    key: 'COLLECTIONS_SETTLEMENTS',
    name: 'Settlements & Debt Relief',
    shortLabel: 'Settlements',
    description: 'One-Time Settlement (OTS) requests, penalty waivers, and loan restructuring',
    portal: 'COLLECTIONS',
    department: 'COLLECTIONS',
    iconName: 'Scale',
    defaultRoute: '/settlements',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'COLLECTIONS_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // FINANCE PORTAL WORKSPACES
  FINANCE_GL: {
    key: 'FINANCE_GL',
    name: 'General Ledger (GL)',
    shortLabel: 'General Ledger',
    description: 'Double-entry trial balance, chart of accounts, and financial MIS statements',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Scale',
    defaultRoute: '/general-ledger',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  FINANCE_TREASURY: {
    key: 'FINANCE_TREASURY',
    name: 'Treasury & Disbursements',
    shortLabel: 'Treasury',
    description: 'Disbursement batch maker-checker, payout execution, and repayment receipts',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Wallet',
    defaultRoute: '/disbursements',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  FINANCE_RECONCILIATION: {
    key: 'FINANCE_RECONCILIATION',
    name: 'Banking & Reconciliation',
    shortLabel: 'Reconciliation',
    description: 'Bank statement 3-way matching, payment gateway settlements, and float audit',
    portal: 'FINANCE',
    department: 'FINANCE',
    iconName: 'Receipt',
    defaultRoute: '/reconciliation',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'FINANCE_OFFICER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // MANAGEMENT PORTAL WORKSPACES
  MANAGEMENT_COMMAND_CENTER: {
    key: 'MANAGEMENT_COMMAND_CENTER',
    name: 'Executive Command Center',
    shortLabel: 'Command Center',
    description: 'Centralized executive operational health, AI telemetry, and portfolio KPI radar',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'Cpu',
    defaultRoute: '/command-center',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'EXECUTIVE'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  MANAGEMENT_ANALYTICS: {
    key: 'MANAGEMENT_ANALYTICS',
    name: 'Portfolio Analytics & MIS',
    shortLabel: 'Analytics',
    description: 'Origination funnel, 2D risk-fraud matrices, collector productivity, and custom reports',
    portal: 'MANAGEMENT',
    department: 'MANAGEMENT',
    iconName: 'BarChart3',
    defaultRoute: '/analytics',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'BRANCH_MANAGER', 'FINANCE_OFFICER'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  MANAGEMENT_EARLY_WARNINGS: {
    key: 'MANAGEMENT_EARLY_WARNINGS',
    name: 'Early Warning Center',
    shortLabel: 'Early Warnings',
    description: 'Pre-delinquency telemetry, bureau degradation alerts, and liquidity forecast',
    portal: 'MANAGEMENT',
    department: 'RISK',
    iconName: 'AlertTriangle',
    defaultRoute: '/early-warnings',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'RISK_MANAGER'],
    displayOrder: 3,
    status: 'ACTIVE',
  },

  // ADMIN PORTAL WORKSPACES
  ADMIN_ACCESS_CONTROL: {
    key: 'ADMIN_ACCESS_CONTROL',
    name: 'Staff & Access Control',
    shortLabel: 'Access Control',
    description: 'User management, RBAC custom roles, permission matrix, and staff directory',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'KeyRound',
    defaultRoute: '/users',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
  ADMIN_RULES_STUDIO: {
    key: 'ADMIN_RULES_STUDIO',
    name: 'BRE & Workflow Studio',
    shortLabel: 'Rules Studio',
    description: 'Business Rule Engine visual editor, approval matrix, and state machine workflows',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'Workflow',
    defaultRoute: '/bre-studio',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 2,
    status: 'ACTIVE',
  },
  ADMIN_CONFIGURATION: {
    key: 'ADMIN_CONFIGURATION',
    name: 'Institutional Config & Branding',
    shortLabel: 'Config & Branding',
    description: 'Multi-tenant lender parameters, loan products, branches, white-label branding, and integrations',
    portal: 'ADMIN',
    department: 'ADMINISTRATION',
    iconName: 'Sliders',
    defaultRoute: '/configuration',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN'],
    displayOrder: 3,
    status: 'ACTIVE',
  },
  ADMIN_AUDIT_COMPLIANCE: {
    key: 'ADMIN_AUDIT_COMPLIANCE',
    name: 'Audit & DPDP Compliance',
    shortLabel: 'Compliance',
    description: 'Immutable SHA-256 evidence packages, DPDP consent registry, and regulatory audits',
    portal: 'ADMIN',
    department: 'COMPLIANCE',
    iconName: 'ShieldCheck',
    defaultRoute: '/compliance',
    allowedRoles: ['SUPER_ADMIN', 'ADMIN', 'COMPANY_ADMIN', 'AUDITOR'],
    displayOrder: 4,
    status: 'ACTIVE',
  },

  // BORROWER WORKSPACE
  BORROWER_SELF_SERVICE: {
    key: 'BORROWER_SELF_SERVICE',
    name: 'Borrower Self-Service Hub',
    shortLabel: 'My Account',
    description: 'Customer application status, KFS acceptance, repayments, and NOC certificates',
    portal: 'BORROWER',
    department: 'CUSTOMER_SERVICE',
    iconName: 'User',
    defaultRoute: '/borrower',
    allowedRoles: ['CUSTOMER', 'SUPER_ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },

  // PARTNER WORKSPACE
  PARTNER_EMBEDDED_HUB: {
    key: 'PARTNER_EMBEDDED_HUB',
    name: 'Partner / LSP Embedded Desk',
    shortLabel: 'Partner Hub',
    description: 'Embedded loan origination pipeline, DSA agents, API keys, and webhook logs',
    portal: 'PARTNER',
    department: 'PARTNER_NETWORK',
    iconName: 'Handshake',
    defaultRoute: '/partner',
    allowedRoles: ['PARTNER', 'SUPER_ADMIN', 'ADMIN'],
    displayOrder: 1,
    status: 'ACTIVE',
  },
};

// 3. Master Navigation Hierarchy Tree
export const MASTER_NAVIGATION: NavigationItemModel[] = [
  // --- OPERATIONS / LENDING ---
  {
    id: 'nav-ops-dashboard',
    label: 'Operations Dashboard',
    icon: 'LayoutDashboard',
    route: '/dashboard',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-ops-apps',
    label: 'Loan Applications',
    icon: 'FileText',
    route: '/applications',
    permission: 'application.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-ops-returned',
    label: 'Returned Applications',
    icon: 'RotateCcw',
    route: '/returned-applications',
    permission: 'application.return',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-ops-loans',
    label: 'Active Loan Accounts',
    icon: 'DollarSign',
    route: '/loans',
    permission: 'loan.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-ops-customers',
    label: 'Customer 360 Directory',
    icon: 'Users',
    route: '/customers',
    permission: 'customer.view',
    workspace: 'OPERATIONS_ONBOARDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-ops-branch-review',
    label: 'Branch Applications Desk',
    icon: 'Building2',
    route: '/branch-review',
    permission: 'approval.view',
    workspace: 'OPERATIONS_BRANCH',
    portal: 'OPERATIONS',
    group: 'WORKFLOW',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-ops-comms',
    label: 'Omnichannel Communications',
    icon: 'Mail',
    route: '/communications',
    permission: 'communication.view',
    workspace: 'OPERATIONS_LENDING',
    portal: 'OPERATIONS',
    group: 'OPERATIONS',
    displayOrder: 7,
    enabled: true,
  },

  // --- CREDIT & RISK ---
  {
    id: 'nav-credit-desk',
    label: 'Credit Assessment Desk',
    icon: 'Calculator',
    route: '/credit-assessment',
    permission: 'credit.assess',
    workspace: 'CREDIT_ASSESSMENT',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-credit-underwriting',
    label: 'Underwriting Queue',
    icon: 'FileCheck',
    route: '/underwriting',
    permission: 'underwriting.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-credit-approval-queue',
    label: 'Approval Authority Queue',
    icon: 'ShieldCheck',
    route: '/approval-queue',
    permission: 'approval.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'WORKFLOW',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-credit-facilities',
    label: 'Credit Facilities & Limits',
    icon: 'Layers',
    route: '/credit-facilities',
    permission: 'credit_limit.view',
    workspace: 'CREDIT_ASSESSMENT',
    portal: 'CREDIT',
    group: 'OPERATIONS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-credit-offers',
    label: 'Offer Engine & KFS',
    icon: 'Receipt',
    route: '/offers',
    permission: 'offer.view',
    workspace: 'CREDIT_UNDERWRITING',
    portal: 'CREDIT',
    group: 'OPERATIONS',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-credit-risk-hub',
    label: 'Risk Intelligence Hub',
    icon: 'Activity',
    route: '/risk',
    permission: 'risk.view',
    workspace: 'CREDIT_RISK_STUDIO',
    portal: 'CREDIT',
    group: 'GOVERNANCE',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-credit-fraud-hub',
    label: 'Fraud Intelligence Hub',
    icon: 'ShieldAlert',
    route: '/fraud',
    permission: 'fraud.view',
    workspace: 'CREDIT_RISK_STUDIO',
    portal: 'CREDIT',
    group: 'GOVERNANCE',
    displayOrder: 7,
    enabled: true,
  },

  // --- COLLECTIONS & RECOVERY ---
  {
    id: 'nav-coll-queue',
    label: 'Collections Delinquency Queue',
    icon: 'AlertCircle',
    route: '/collections',
    permission: 'collections.view',
    workspace: 'COLLECTIONS_DELINQUENCY',
    portal: 'COLLECTIONS',
    group: 'WORKFLOW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-coll-npa',
    label: 'NPA & Asset Quality',
    icon: 'AlertTriangle',
    route: '/npa-monitoring',
    permission: 'collections.view',
    workspace: 'COLLECTIONS_RECOVERY',
    portal: 'COLLECTIONS',
    group: 'OPERATIONS',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-coll-settlements',
    label: 'Debt Settlements (OTS)',
    icon: 'Scale',
    route: '/settlements',
    permission: 'collections.settlement.view',
    workspace: 'COLLECTIONS_SETTLEMENTS',
    portal: 'COLLECTIONS',
    group: 'OPERATIONS',
    displayOrder: 3,
    enabled: true,
  },

  // --- FINANCE & ACCOUNTING ---
  {
    id: 'nav-fin-gl',
    label: 'General Ledger (GL)',
    icon: 'Scale',
    route: '/general-ledger',
    permission: 'accounting.view',
    workspace: 'FINANCE_GL',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-fin-disbursements',
    label: 'Disbursement Batches',
    icon: 'Wallet',
    route: '/disbursements',
    permission: 'disbursement.view',
    workspace: 'FINANCE_TREASURY',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-fin-payments',
    label: 'Payments & Collections Ledger',
    icon: 'Receipt',
    route: '/payments',
    permission: 'payment.view',
    workspace: 'FINANCE_TREASURY',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-fin-recon',
    label: 'Banking & Reconciliation',
    icon: 'Scale',
    route: '/reconciliation',
    permission: 'reconciliation.view',
    workspace: 'FINANCE_RECONCILIATION',
    portal: 'FINANCE',
    group: 'FINANCE',
    displayOrder: 4,
    enabled: true,
  },

  // --- MANAGEMENT & ANALYTICS ---
  {
    id: 'nav-mgmt-cmd',
    label: 'Executive Command Center',
    icon: 'Cpu',
    route: '/command-center',
    permission: 'analytics.command_center',
    workspace: 'MANAGEMENT_COMMAND_CENTER',
    portal: 'MANAGEMENT',
    group: 'OVERVIEW',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-mgmt-analytics',
    label: 'Portfolio Analytics Hub',
    icon: 'BarChart3',
    route: '/analytics',
    permission: 'analytics.view',
    workspace: 'MANAGEMENT_ANALYTICS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-mgmt-reports',
    label: 'MIS Reports & Exports',
    icon: 'FileText',
    route: '/reports',
    permission: 'report.view',
    workspace: 'MANAGEMENT_ANALYTICS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-mgmt-early-warnings',
    label: 'Early Warnings Center',
    icon: 'AlertTriangle',
    route: '/early-warnings',
    permission: 'risk.view',
    workspace: 'MANAGEMENT_EARLY_WARNINGS',
    portal: 'MANAGEMENT',
    group: 'REPORTS',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-mgmt-operations',
    label: 'Operations Observability',
    icon: 'Activity',
    route: '/operations',
    permission: 'operations.view',
    workspace: 'MANAGEMENT_COMMAND_CENTER',
    portal: 'MANAGEMENT',
    group: 'OVERVIEW',
    displayOrder: 5,
    enabled: true,
  },

  // --- ADMINISTRATION & GOVERNANCE ---
  {
    id: 'nav-adm-users',
    label: 'Staff Directory & Users',
    icon: 'KeyRound',
    route: '/users',
    permission: 'user.view',
    workspace: 'ADMIN_ACCESS_CONTROL',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-adm-roles',
    label: 'RBAC Custom Roles',
    icon: 'ShieldCheck',
    route: '/roles',
    permission: 'role.view',
    workspace: 'ADMIN_ACCESS_CONTROL',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 2,
    enabled: true,
  },
  {
    id: 'nav-adm-bre',
    label: 'BRE Rule Studio',
    icon: 'Sliders',
    route: '/bre-studio',
    permission: 'bre.view',
    workspace: 'ADMIN_RULES_STUDIO',
    portal: 'ADMIN',
    group: 'GOVERNANCE',
    displayOrder: 3,
    enabled: true,
  },
  {
    id: 'nav-adm-workflows',
    label: 'State Machine Workflows',
    icon: 'Workflow',
    route: '/workflows',
    permission: 'workflow.view',
    workspace: 'ADMIN_RULES_STUDIO',
    portal: 'ADMIN',
    group: 'GOVERNANCE',
    displayOrder: 4,
    enabled: true,
  },
  {
    id: 'nav-adm-authority',
    label: 'Approval Authority Matrix',
    icon: 'ShieldCheck',
    route: '/authority-matrix',
    permission: 'authority.view',
    workspace: 'ADMIN_RULES_STUDIO',
    portal: 'ADMIN',
    group: 'GOVERNANCE',
    displayOrder: 5,
    enabled: true,
  },
  {
    id: 'nav-adm-config',
    label: 'Institutional Parameters',
    icon: 'Sliders',
    route: '/configuration',
    permission: 'configuration.view',
    workspace: 'ADMIN_CONFIGURATION',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 6,
    enabled: true,
  },
  {
    id: 'nav-adm-tenants',
    label: 'Lender Tenants',
    icon: 'Layers',
    route: '/tenants',
    permission: 'tenant.view',
    workspace: 'ADMIN_CONFIGURATION',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 7,
    enabled: true,
  },
  {
    id: 'nav-adm-branches',
    label: 'Branch Network Directory',
    icon: 'Building2',
    route: '/branches',
    permission: 'branch.view',
    workspace: 'ADMIN_CONFIGURATION',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 8,
    enabled: true,
  },
  {
    id: 'nav-adm-products',
    label: 'Loan Product Catalog',
    icon: 'Building2',
    route: '/loan-products',
    permission: 'product.view',
    workspace: 'ADMIN_CONFIGURATION',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 9,
    enabled: true,
  },
  {
    id: 'nav-adm-branding',
    label: 'White-Label Branding',
    icon: 'Palette',
    route: '/branding',
    permission: 'branding.view',
    workspace: 'ADMIN_CONFIGURATION',
    portal: 'ADMIN',
    group: 'SETTINGS',
    displayOrder: 10,
    enabled: true,
  },
  {
    id: 'nav-adm-compliance',
    label: 'Regulatory & DPDP Audit',
    icon: 'ShieldCheck',
    route: '/compliance',
    permission: 'compliance.view',
    workspace: 'ADMIN_AUDIT_COMPLIANCE',
    portal: 'ADMIN',
    group: 'GOVERNANCE',
    displayOrder: 11,
    enabled: true,
  },
  {
    id: 'nav-adm-audit-logs',
    label: 'Immutable Audit Trail',
    icon: 'ScrollText',
    route: '/audit-logs',
    permission: 'audit.view',
    workspace: 'ADMIN_AUDIT_COMPLIANCE',
    portal: 'ADMIN',
    group: 'GOVERNANCE',
    displayOrder: 12,
    enabled: true,
  },

  // --- PARTNERS & EMBEDDED ---
  {
    id: 'nav-partner-desk',
    label: 'Partner Origination Desk',
    icon: 'Handshake',
    route: '/partners',
    permission: 'partner.view',
    workspace: 'PARTNER_EMBEDDED_HUB',
    portal: 'PARTNER',
    group: 'OPERATIONS',
    displayOrder: 1,
    enabled: true,
  },
  {
    id: 'nav-partner-portal',
    label: 'LSP / Embedded Portal',
    icon: 'Layers',
    route: '/partner',
    permission: 'partner.view',
    workspace: 'PARTNER_EMBEDDED_HUB',
    portal: 'PARTNER',
    group: 'OPERATIONS',
    displayOrder: 2,
    enabled: true,
  },
];

// 4. Default Department-to-Workspace Default Mapping
export const ROLE_DEPARTMENT_MAP: Record<string, DepartmentKey> = {
  SUPER_ADMIN: 'ADMINISTRATION',
  ADMIN: 'ADMINISTRATION',
  COMPANY_ADMIN: 'MANAGEMENT',
  LOAN_OFFICER: 'OPERATIONS',
  BRANCH_MANAGER: 'OPERATIONS',
  CREDIT_ANALYST: 'CREDIT',
  UNDERWRITER: 'CREDIT',
  RISK_ANALYST: 'RISK',
  RISK_MANAGER: 'RISK',
  FRAUD_ANALYST: 'RISK',
  COLLECTION_OFFICER: 'COLLECTIONS',
  COLLECTIONS_MANAGER: 'COLLECTIONS',
  FINANCE_OFFICER: 'FINANCE',
  AUDITOR: 'COMPLIANCE',
  CUSTOMER: 'CUSTOMER_SERVICE',
  PARTNER: 'PARTNER_NETWORK',
};

// 5. Default Feature Flags
export const DEFAULT_FEATURE_FLAGS: FeatureFlagConfig = {
  enableBreStudio: true,
  enableAiCommandCenter: true,
  enableDigiLockerKyc: true,
  enableInstantEnach: true,
  enableCollectionsAutomation: true,
  enableAdvancedReporting: true,
  enableWhiteLabelBranding: true,
  enableBorrowerApp: true,
  enablePartnerLspPlatform: true,
};
