export const SALARY_PATTERNS = [
  /\b(SALARY|SAL|PAYROLL|CMS\/|SAL CR|NET SALARY|SALARY CREDIT|MONTHLY SALARY|SAL-CREDIT|DIR DEP)\b/i,
  /\bBY SALARY\b/i,
  /\bSALARY FOR\b/i,
  /\bSALARY CREDIT\b/i,
  /\bACH CR.*(SALARY|PAYROLL)\b/i,
  /\bCMS\/.*SAL\b/i,
];

export const EMI_PATTERNS = [
  /\b(NACH|ACH|ECS|LOAN|EMI|LENDER|FINANCE|CAPITAL|CREDITBEE|KREDITBEE|BAJAJ|BAJAJ FIN|MUTHOOT|CHOLAMANDALAM|FULLERTON|POONAWALLA|PIRAMAL|TATA CAPITAL|HDFC LOAN|ICICI LOAN|KOTAK LOAN|IDFC FIRST LOAN|SHRIRAM|HOME CREDIT|FIBE|MONEYTAP|CASHE|CRED|SLICE|ZESTMONEY)\b/i,
  /\b(LOAN REPAYMENT|EMI DEBIT|AUTO DEBIT LOAN|ACH DR)\b/i,
];

export const CREDIT_CARD_PATTERNS = [
  /\b(CREDIT CARD|CC PAYMENT|CC PYMT|SBICARD|HDFCCC|ICICICC|AMEX|AXIS CC|RBL CC|CITI CC|CRED CC)\b/i,
];

export const RENT_PATTERNS = [
  /\b(RENT|HOUSE RENT|FLAT RENT|ROOM RENT|PG RENT|MONTHLY RENT|RENT PAYMENT|OFFICE RENT)\b/i,
];

export const UTILITY_PATTERNS = [
  /\b(ELECTRICITY|POWER|WATER BILL|GAS BILL|BESCOM|TNEB|MSEDCL|BSES|CESC|AIRTEL|JIO|VODAFONE|VI BILL|BROADBAND|DTH|TATA PLAY|INDRAPRASTHA GAS|MAHANAGAR GAS|ADANI TOTAL GAS)\b/i,
];

export const CASH_PATTERNS = [
  /\b(ATM|CASH WDL|NFS|ATM CASH|CASH WITHDRAWAL|MATM|CWDR)\b/i,
  /\b(CASH DEP|CDM DEP|CASH DEPOSIT)\b/i,
];

export const INVESTMENT_PATTERNS = [
  /\b(MUTUAL FUND|SIP|ZERODHA|GROWW|UPSTOX|NSE|BSE|DEMAT|DIVIDEND|INTEREST CR|FIXED DEP|RECURRING DEP)\b/i,
];

export const LENDING_ENTITIES_MAP: Record<string, string> = {
  BAJAJ: 'Bajaj Finance',
  HDFC: 'HDFC Bank Lending',
  ICICI: 'ICICI Bank Retail Loan',
  KOTAK: 'Kotak Mahindra Prime',
  TATA: 'Tata Capital',
  CHOLA: 'Cholamandalam Investment',
  MUTHOOT: 'Muthoot Finance',
  PIRAMAL: 'Piramal Capital',
  KREDITBEE: 'KreditBee NBFC',
  CRED: 'CRED Cash',
  SLICE: 'Slice Credit',
  FIBE: 'Fibe (EarlySalary)',
  SHRIRAM: 'Shriram Finance',
  POONA: 'Poonawalla Fincorp',
  FULLER: 'Fullerton / SMFG India',
  IDFC: 'IDFC FIRST Bank Loans',
};
